// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const deleteActivityEventsByOrg = `-- name: DeleteActivityEventsByOrg :exec
DELETE FROM activity_events
WHERE organisation_id = $1
`

func (q *Queries) DeleteActivityEventsByOrg(ctx context.Context, organisationID string) error {
	_, err := q.db.Exec(ctx, deleteActivityEventsByOrg, organisationID)
	return err
}

const insertActivityEvent = `-- name: InsertActivityEvent :one
INSERT INTO activity_events (
    id,
    organisation_id,
    organisation_slug,
    organisation_name,
    actor_type,
    actor_id,
    actor_label,
    action,
    resource_type,
    resource_id,
    summary,
    payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, organisation_id, organisation_slug, organisation_name, actor_type, actor_id, actor_label, action, resource_type, resource_id, summary, payload, created_at
`

type InsertActivityEventParams struct {
	ID               string          `json:"id"`
	OrganisationID   string          `json:"organisation_id"`
	OrganisationSlug string          `json:"organisation_slug"`
	OrganisationName string          `json:"organisation_name"`
	ActorType        string          `json:"actor_type"`
	ActorID          string          `json:"actor_id"`
	ActorLabel       string          `json:"actor_label"`
	Action           string          `json:"action"`
	ResourceType     string          `json:"resource_type"`
	ResourceID       string          `json:"resource_id"`
	Summary          string          `json:"summary"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, insertActivityEvent,
		arg.ID,
		arg.OrganisationID,
		arg.OrganisationSlug,
		arg.OrganisationName,
		arg.ActorType,
		arg.ActorID,
		arg.ActorLabel,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Summary,
		arg.Payload,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.OrganisationSlug,
		&i.OrganisationName,
		&i.ActorType,
		&i.ActorID,
		&i.ActorLabel,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Summary,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityEventsByOrg = `-- name: ListActivityEventsByOrg :many
SELECT id, organisation_id, organisation_slug, organisation_name, actor_type, actor_id, actor_label, action, resource_type, resource_id, summary, payload, created_at
FROM activity_events
WHERE organisation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListActivityEventsByOrgParams struct {
	OrganisationID string `json:"organisation_id"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListActivityEventsByOrg(ctx context.Context, arg ListActivityEventsByOrgParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listActivityEventsByOrg, arg.OrganisationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.OrganisationSlug,
			&i.OrganisationName,
			&i.ActorType,
			&i.ActorID,
			&i.ActorLabel,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Summary,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
