// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type ActivityEvent struct {
	ID               string          `json:"id"`
	OrganisationID   string          `json:"organisation_id"`
	OrganisationSlug string          `json:"organisation_slug"`
	OrganisationName string          `json:"organisation_name"`
	ActorType        string          `json:"actor_type"`
	ActorID          string          `json:"actor_id"`
	ActorLabel       string          `json:"actor_label"`
	Action           string          `json:"action"`
	ResourceType     string          `json:"resource_type"`
	ResourceID       string          `json:"resource_id"`
	Summary          string          `json:"summary"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
}

type UsageCounter struct {
	OrganisationID string    `json:"organisation_id"`
	MeterKey       string    `json:"meter_key"`
	PeriodStart    time.Time `json:"period_start"`
	Dim1Key        string    `json:"dim1_key"`
	Dim1Value      string    `json:"dim1_value"`
	Dim2Key        string    `json:"dim2_key"`
	Dim2Value      string    `json:"dim2_value"`
	Count          int64     `json:"count"`
	UpdatedAt      time.Time `json:"updated_at"`
}
