// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUsageCountersByOrg = `-- name: DeleteUsageCountersByOrg :exec
DELETE FROM usage_counters
WHERE organisation_id = $1
`

func (q *Queries) DeleteUsageCountersByOrg(ctx context.Context, organisationID string) error {
	_, err := q.db.Exec(ctx, deleteUsageCountersByOrg, organisationID)
	return err
}

const incrUsageCounter = `-- name: IncrUsageCounter :one
INSERT INTO usage_counters (
    organisation_id,
    meter_key,
    period_start,
    dim1_key,
    dim1_value,
    dim2_key,
    dim2_value,
    count,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
ON CONFLICT (
    organisation_id,
    meter_key,
    period_start,
    dim1_key,
    dim1_value,
    dim2_key,
    dim2_value
) DO UPDATE SET
    count = usage_counters.count + EXCLUDED.count,
    updated_at = now()
RETURNING organisation_id, meter_key, period_start, dim1_key, dim1_value, dim2_key, dim2_value, count, updated_at
`

type IncrUsageCounterParams struct {
	OrganisationID string    `json:"organisation_id"`
	MeterKey       string    `json:"meter_key"`
	PeriodStart    time.Time `json:"period_start"`
	Dim1Key        string    `json:"dim1_key"`
	Dim1Value      string    `json:"dim1_value"`
	Dim2Key        string    `json:"dim2_key"`
	Dim2Value      string    `json:"dim2_value"`
	Count          int64     `json:"count"`
}

func (q *Queries) IncrUsageCounter(ctx context.Context, arg IncrUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, incrUsageCounter,
		arg.OrganisationID,
		arg.MeterKey,
		arg.PeriodStart,
		arg.Dim1Key,
		arg.Dim1Value,
		arg.Dim2Key,
		arg.Dim2Value,
		arg.Count,
	)
	var i UsageCounter
	err := row.Scan(
		&i.OrganisationID,
		&i.MeterKey,
		&i.PeriodStart,
		&i.Dim1Key,
		&i.Dim1Value,
		&i.Dim2Key,
		&i.Dim2Value,
		&i.Count,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsageCountersByOrgPeriod = `-- name: ListUsageCountersByOrgPeriod :many
SELECT organisation_id, meter_key, period_start, dim1_key, dim1_value, dim2_key, dim2_value, count, updated_at
FROM usage_counters
WHERE organisation_id = $1
  AND period_start >= $2
  AND period_start < $3
ORDER BY meter_key, dim1_key, dim1_value, dim2_key, dim2_value
`

type ListUsageCountersByOrgPeriodParams struct {
	OrganisationID string    `json:"organisation_id"`
	FromPeriod     time.Time `json:"from_period"`
	ToPeriod       time.Time `json:"to_period"`
}

func (q *Queries) ListUsageCountersByOrgPeriod(ctx context.Context, arg ListUsageCountersByOrgPeriodParams) ([]UsageCounter, error) {
	rows, err := q.db.Query(ctx, listUsageCountersByOrgPeriod, arg.OrganisationID, arg.FromPeriod, arg.ToPeriod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCounter{}
	for rows.Next() {
		var i UsageCounter
		if err := rows.Scan(
			&i.OrganisationID,
			&i.MeterKey,
			&i.PeriodStart,
			&i.Dim1Key,
			&i.Dim1Value,
			&i.Dim2Key,
			&i.Dim2Value,
			&i.Count,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
