import { useEffect, useMemo, useState } from 'react'
import {
  Background,
  Controls,
  Handle,
  MiniMap,
  Position,
  ReactFlow,
  ReactFlowProvider,
  type Edge,
  type NodeProps,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { layout, type SchemaGraph, type SchemaNode } from './schema_layout'

/**
 * The authorisation model, drawn.
 *
 * This is documentation rather than a control, which is why it lives here and
 * not in the organisation sidebar: KYC's schema is the same for every tenant
 * and none of them can change it. A merchant's own schema is the opposite case,
 * and when that tier is modelled it earns a page they can act on.
 *
 * The graph is a build artefact, generated by `make openapi` from the same
 * string the evaluator loads, so it cannot drift from the model and it renders
 * without a session.
 */
export function DocsAuthorisationPage() {
  const [graph, setGraph] = useState<SchemaGraph | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let live = true
    void fetch('/access-schema.json')
      .then((r) => {
        if (!r.ok) throw new Error(`${r.status} ${r.statusText}`)
        return r.json() as Promise<SchemaGraph>
      })
      .then((g) => live && setGraph(g))
      .catch((e) => live && setError(e instanceof Error ? e.message : 'Could not load the schema'))
    return () => {
      live = false
    }
  }, [])

  if (error) return <p className="error">{error}</p>
  if (!graph) return <p className="app-muted">Loading the schema…</p>

  return (
    <article className="docs-concepts prose-docs">
      <h1>Authorisation</h1>
      <p className="lede">
        Every gate resolves by walking this graph. Types are nodes, relations are
        arrows, and the rules inside a node are how that type answers an action.
      </p>

      <SchemaSummary graph={graph} />

      <div className="schema-canvas">
        <ReactFlowProvider>
          <SchemaFlow graph={graph} />
        </ReactFlowProvider>
      </div>

      <p className="app-muted schema-caption">
        Drag a node to rearrange. Diamonds are not declared types: they stand for
        a set of targets that several relations share, drawn once so the picture
        shows the model rather than the repetition.
      </p>

      <Shapes graph={graph} />

      <h2>Reading a rule</h2>
      <p>
        A rule is a set expression, evaluated at one point. <code>+</code> is
        union, <code>&amp;</code> is intersection, <code>-</code> subtracts, and{' '}
        <code>-&gt;</code> walks a relation and asks again at the far end.
      </p>
      <p>
        The organisation type is worth reading closely:{' '}
        <code>member = belongs - suspended + oversees</code>. A member of a
        suspended tenant loses reach, while a platform principal holding{' '}
        <code>oversees</code> keeps it, because that term sits outside the
        subtraction. That is what lets a suspended tenant still be seen and
        restored, rather than suspension becoming a one-way door.
      </p>

      <h2>Why the schema, and not the edges</h2>
      <p>
        This draws what the model permits, never who currently holds what. A
        schema is a couple of dozen types whatever the tenant; the edge set grows
        with the business, and a picture of all of it is unreadable at every size
        a real tenant reaches. Bounded views of the edges are a separate thing:{' '}
        <strong>Members</strong> shows one person's decisions with the route the
        walk took to each.
      </p>
    </article>
  )
}

function SchemaSummary({ graph }: { graph: SchemaGraph }) {
  const s = graph.summary
  return (
    <dl className="schema-summary">
      <Stat label="namespace" value={graph.namespace} />
      <Stat label="types" value={s.types} />
      <Stat label="relations" value={s.relations} />
      <Stat label="actions" value={s.actions} />
      <Stat label="rules" value={s.rules} />
      <Stat
        label="wildcard"
        value={s.wildcards}
        hint="relations that accept a star node, where one edge can confer reach over everything of a type"
      />
      <Stat
        label="transitive"
        value={s.transitive}
        hint="relations the walk follows to closure, which is the whole grouping mechanism"
      />
    </dl>
  )
}

function Stat({ label, value, hint }: { label: string; value: string | number; hint?: string }) {
  return (
    <div className="schema-stat" title={hint}>
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  )
}

function Shapes({ graph }: { graph: SchemaGraph }) {
  const shapes = graph.shapes ?? []
  if (shapes.length === 0) return null
  return (
    <>
      <h2>Repeated shapes</h2>
      <p>
        These types declare the same relations pointing at the same places{' '}
        <em>and</em> answer the same actions the same way, so they differ only in
        their name. Both halves matter: more types than this hang off{' '}
        <code>organisation</code> and look alike in the picture above, while
        answering different sets of actions.
      </p>
      <ul className="schema-shapes">
        {shapes.map((shape) => (
          <li key={shape.types.join(',')}>
            <strong>{shape.types.length} types</strong>
            <span>{shape.types.join(', ')}</span>
            {shape.rules && shape.rules.length > 0 && (
              <span className="schema-shape-rules">{shape.rules.join('  ·  ')}</span>
            )}
          </li>
        ))}
      </ul>
    </>
  )
}

function SchemaFlow({ graph }: { graph: SchemaGraph }) {
  const nodes = useMemo(() => layout(graph), [graph])
  const edges: Edge[] = useMemo(
    () =>
      graph.edges.map((e) => ({
        id: e.id,
        source: e.from,
        target: e.to,
        label: e.label,
        // Grant relations all point at the same principal set, so several
        // arrows share a corridor. A curve keeps them apart where a straight
        // line would overlap them into one.
        type: 'bezier',
      })),
    [graph],
  )

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      nodeTypes={schemaNodeTypes}
      fitView
      fitViewOptions={{ padding: 0.15 }}
      nodesConnectable={false}
      panOnScroll
      zoomOnScroll
      minZoom={0.2}
      proOptions={{ hideAttribution: true }}
    >
      <Background gap={16} size={1} />
      <Controls showInteractive={false} />
      <MiniMap pannable zoomable />
    </ReactFlow>
  )
}

function SchemaTypeNode({ data }: NodeProps) {
  const node = (data as { node: SchemaNode }).node
  const isSet = node.kind === 'set'
  return (
    <div className={isSet ? 'schema-node schema-node-set' : 'schema-node'}>
      <Handle type="target" position={Position.Left} />
      <p className="schema-node-name">{node.label}</p>
      {node.rules && node.rules.length > 0 && (
        <ul className="schema-node-rules">
          {node.rules.map((r) => (
            <li key={r.action}>
              <span className="schema-action">{r.action}</span>
              <span className="schema-eq">=</span>
              <span className="schema-expr">{r.expr}</span>
            </li>
          ))}
        </ul>
      )}
      <Handle type="source" position={Position.Right} />
    </div>
  )
}

const schemaNodeTypes = { schema: SchemaTypeNode }
