// Command openapi-filter writes a customer Integration API subset of the full OpenAPI spec.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// integrationPaths lists path templates included in the merchant Integration API.
// Method maps with empty slice mean all methods; otherwise only listed verbs.
var integrationPaths = map[string][]string{
	"/v1/organisations/{id}":                         {"get"},
	"/v1/organisations/{id}/app-users":                nil,
	"/v1/organisations/{id}/app-users/ingest":         nil,
	"/v1/app-users/{id}":                             nil,
	"/v1/organisations/{id}/attribute-definitions":   nil,
	"/v1/attribute-definitions/{id}":                 nil,
	"/v1/organisations/{id}/product-features":        nil,
	"/v1/product-features/{id}":                      nil,
	"/v1/organisations/{id}/feature-flags":           nil,
	"/v1/feature-flags/{id}":                         nil,
	"/v1/feature-flags/{id}/overrides":               {"put"},
	"/v1/feature-flags/check":                        {"post"},
	"/v1/organisations/{id}/product-plans":           nil,
	"/v1/product-plans/{id}":                         nil,
	"/v1/product-plans/{id}/features":                nil,
	"/v1/product-plans/{id}/price":                   nil,
	"/v1/product-plans/{id}/prices":                  nil,
	"/v1/organisations/{id}/product-plan":            nil,
	"/v1/organisations/{id}/entitlements":            {"get"},
	"/v1/organisations/{id}/subscription":            {"get"},
	"/v1/entitlements/check":                         {"post"},
	"/v1/plans":                                      {"get"},
	"/v1/plans/{id}":                                 {"get"},
	"/v1/plans/{id}/prices":                          {"get"},
	"/v1/entitlements":                               {"get"},
	"/v1/hooks/inbound/{hookId}":                     {"post"},
	"/v1/hooks/inbound/{hookId}/{token}":             {"post"},
	"/v1/public/organisations/{id}/branding/logo":    {"get"},
}

var httpMethods = map[string]bool{
	"get": true, "put": true, "post": true, "delete": true, "options": true,
	"head": true, "patch": true, "trace": true,
}

func main() {
	inPath := flag.String("in", "docs/openapi.yaml", "input OpenAPI file")
	outPath := flag.String("out", "web/public/openapi-integration.yaml", "output OpenAPI file")
	flag.Parse()

	raw, err := os.ReadFile(*inPath)
	if err != nil {
		fail(err)
	}
	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fail(err)
	}

	paths, _ := doc["paths"].(map[string]any)
	if paths == nil {
		fail(fmt.Errorf("openapi: missing paths"))
	}
	filtered := map[string]any{}
	usedTags := map[string]struct{}{}
	for path, allowMethods := range integrationPaths {
		item, ok := paths[path]
		if !ok {
			fail(fmt.Errorf("openapi: missing path %s", path))
		}
		ops, ok := item.(map[string]any)
		if !ok {
			fail(fmt.Errorf("openapi: invalid path item %s", path))
		}
		keep := map[string]any{}
		for k, v := range ops {
			lk := strings.ToLower(k)
			if !httpMethods[lk] {
				keep[k] = v // parameters, servers, etc.
				continue
			}
			if allowMethods != nil && !containsFold(allowMethods, lk) {
				continue
			}
			op, ok := v.(map[string]any)
			if !ok {
				continue
			}
			keep[k] = op
			if tags, ok := op["tags"].([]any); ok {
				for _, t := range tags {
					if s, ok := t.(string); ok {
						usedTags[s] = struct{}{}
					}
				}
			}
		}
		hasOp := false
		for k := range keep {
			if httpMethods[strings.ToLower(k)] {
				hasOp = true
				break
			}
		}
		if hasOp {
			filtered[path] = keep
		}
	}
	doc["paths"] = filtered

	if tags, ok := doc["tags"].([]any); ok {
		var kept []any
		for _, t := range tags {
			tm, ok := t.(map[string]any)
			if !ok {
				continue
			}
			name, _ := tm["name"].(string)
			if _, ok := usedTags[name]; ok {
				kept = append(kept, t)
			}
		}
		doc["tags"] = kept
	}

	info, _ := doc["info"].(map[string]any)
	if info == nil {
		info = map[string]any{}
		doc["info"] = info
	}
	info["title"] = "KYC Integration API"
	info["description"] = strings.TrimSpace(`
JSON API for merchant backends integrating with KYC (app users, attributes, product plans, entitlements, feature flags).

Authenticate with an **organisation API key**: ` + "`Authorization: Bearer kyc_…`" + ` (create keys under Platform → API keys).
Keys may be scoped to RBAC permissions; empty scopes grant full organisation access. The organisation must have the ` + "`api_access`" + ` entitlement.

Operator UI routes (Google OAuth, members, roles, permissions, email/automation config, platform admin) are documented separately under **Operator API**.
`)

	out, err := yaml.Marshal(doc)
	if err != nil {
		fail(err)
	}
	header := "# Generated by go run ./cmd/openapi-filter — do not edit.\n# Source: " + *inPath + "\n"
	if err := os.WriteFile(*outPath, append([]byte(header), out...), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d paths)\n", *outPath, len(filtered))
}

func containsFold(list []string, want string) bool {
	for _, s := range list {
		if strings.EqualFold(s, want) {
			return true
		}
	}
	return false
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
