import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import {
  Background,
  Controls,
  Handle,
  MiniMap,
  Position,
  ReactFlow,
  ReactFlowProvider,
  type Edge,
  type NodeProps,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { PageHeader } from '../../crud/ui'
import { resourcePath } from '../../org_nav'
import { layout, type SchemaGraph, type SchemaNode } from './schema_layout'

/**
 * The authorisation model, drawn.
 *
 * It sits under platform capabilities because that group is what the
 * organisation uses inside KYC, and this is KYC's own model: the same for every
 * tenant, and not something a tenant can edit. A merchant's own model is a
 * different graph and belongs in customer access, once that tier is on the
 * graph.
 *
 * The graph is a build artefact generated by `make openapi` from the same
 * string the evaluator loads, so it cannot drift from what actually decides.
 */
export function AuthorisationPage() {
  const { orgId = '' } = useParams()
  const [graph, setGraph] = useState<SchemaGraph | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let live = true
    void fetch('/access-schema.json')
      .then((r) => {
        if (!r.ok) throw new Error(`${r.status} ${r.statusText}`)
        return r.json() as Promise<SchemaGraph>
      })
      .then((g) => live && setGraph(g))
      .catch((e) => live && setError(e instanceof Error ? e.message : 'Could not load the schema'))
    return () => {
      live = false
    }
  }, [])

  if (error) return <p className="error">{error}</p>
  if (!graph) return <p className="app-muted">Loading the schema…</p>

  return (
    <section>
      <PageHeader title="Authorisation" />
      <p className="lede">
        Every permission check resolves by walking this graph. Types are nodes,
        relations are arrows, and the rules inside a node are how that type
        answers an action. It is the same for every organisation.
      </p>

      <SchemaSummary graph={graph} />

      <div className="schema-canvas">
        <ReactFlowProvider>
          <SchemaFlow graph={graph} />
        </ReactFlowProvider>
      </div>

      <p className="app-muted schema-caption">
        Drag a node to rearrange. Diamonds are not declared types: they stand for
        a set of targets that several relations share, drawn once so the picture
        shows the model rather than the repetition.
      </p>

      <Shapes graph={graph} />

      <h3 className="schema-heading">Reading a rule</h3>
      <p className="schema-prose">
        A rule is a set expression, evaluated at one point. <code>+</code> is
        union, <code>&amp;</code> is intersection, <code>-</code> subtracts, and{' '}
        <code>-&gt;</code> walks a relation and asks again at the far end.
      </p>
      <p className="schema-prose">
        The organisation type is worth reading closely:{' '}
        <code>member = belongs - suspended + oversees</code>. A member of a
        suspended organisation loses reach, while KYC staff holding{' '}
        <code>oversees</code> keep it, because that term sits outside the
        subtraction. That is what lets a suspended organisation still be seen and
        restored, rather than suspension becoming a one-way door.
      </p>

      <h3 className="schema-heading">This is the model, not who holds what</h3>
      <p className="schema-prose">
        The picture shows what the model permits, never who currently has access.
        For one person's actual permissions, with the route the check took to
        each answer, open a member from{' '}
        <Link to={resourcePath(orgId, 'members')}>Members</Link>.
      </p>
    </section>
  )
}

function SchemaSummary({ graph }: { graph: SchemaGraph }) {
  const s = graph.summary
  return (
    <dl className="schema-summary">
      <Stat label="types" value={s.types} />
      <Stat label="relations" value={s.relations} />
      <Stat label="actions" value={s.actions} />
      <Stat label="rules" value={s.rules} />
      <Stat
        label="wildcard"
        value={s.wildcards}
        hint="Relations that accept a star node, where one edge can confer reach over everything of a type."
      />
      <Stat
        label="transitive"
        value={s.transitive}
        hint="Relations the walk follows to closure. This is the whole grouping mechanism."
      />
    </dl>
  )
}

function Stat({ label, value, hint }: { label: string; value: string | number; hint?: string }) {
  return (
    <div className="schema-stat" title={hint}>
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  )
}

function Shapes({ graph }: { graph: SchemaGraph }) {
  const shapes = graph.shapes ?? []
  if (shapes.length === 0) return null
  return (
    <>
      <h3 className="schema-heading">Repeated shapes</h3>
      <p className="schema-prose">
        These types declare the same relations pointing at the same places{' '}
        <em>and</em> answer the same actions the same way, so they differ only in
        their name. Both halves matter: more types than this hang off{' '}
        <code>organisation</code> and look alike in the picture above, while
        answering different sets of actions.
      </p>
      <ul className="schema-shapes">
        {shapes.map((shape) => (
          <li key={shape.types.join(',')}>
            <strong>{shape.types.length} types</strong>
            <span>{shape.types.join(', ')}</span>
            {shape.rules && shape.rules.length > 0 && (
              <span className="schema-shape-rules">{shape.rules.join('  ·  ')}</span>
            )}
          </li>
        ))}
      </ul>
    </>
  )
}

function SchemaFlow({ graph }: { graph: SchemaGraph }) {
  const nodes = useMemo(() => layout(graph), [graph])
  const edges: Edge[] = useMemo(
    () =>
      graph.edges.map((e) => ({
        id: e.id,
        source: e.from,
        target: e.to,
        label: e.label,
        // Grant relations all point at the same principal set, so several
        // arrows share a corridor. A curve keeps them apart where a straight
        // line would overlap them into one.
        type: 'bezier',
      })),
    [graph],
  )

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      nodeTypes={schemaNodeTypes}
      fitView
      fitViewOptions={{ padding: 0.15 }}
      nodesConnectable={false}
      panOnScroll
      zoomOnScroll
      minZoom={0.2}
      proOptions={{ hideAttribution: true }}
    >
      <Background gap={16} size={1} />
      <Controls showInteractive={false} />
      <MiniMap pannable zoomable />
    </ReactFlow>
  )
}

function SchemaTypeNode({ data }: NodeProps) {
  const node = (data as { node: SchemaNode }).node
  const isSet = node.kind === 'set'
  return (
    <div className={isSet ? 'schema-node schema-node-set' : 'schema-node'}>
      <Handle type="target" position={Position.Left} />
      <p className="schema-node-name">{node.label}</p>
      {node.rules && node.rules.length > 0 && (
        <ul className="schema-node-rules">
          {node.rules.map((r) => (
            <li key={r.action}>
              <span className="schema-action">{r.action}</span>
              <span className="schema-eq">=</span>
              <span className="schema-expr">{r.expr}</span>
            </li>
          ))}
        </ul>
      )}
      <Handle type="source" position={Position.Right} />
    </div>
  )
}

const schemaNodeTypes = { schema: SchemaTypeNode }
