// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAppRoleExtends = `-- name: AddAppRoleExtends :exec
INSERT INTO app_role_extends (role_id, parent_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAppRoleExtendsParams struct {
	RoleID   string `json:"role_id"`
	ParentID string `json:"parent_id"`
}

func (q *Queries) AddAppRoleExtends(ctx context.Context, arg AddAppRoleExtendsParams) error {
	_, err := q.db.Exec(ctx, addAppRoleExtends, arg.RoleID, arg.ParentID)
	return err
}

const addAppUserToGroup = `-- name: AddAppUserToGroup :exec
INSERT INTO app_user_group_members (group_id, app_user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAppUserToGroupParams struct {
	GroupID   string `json:"group_id"`
	AppUserID string `json:"app_user_id"`
}

func (q *Queries) AddAppUserToGroup(ctx context.Context, arg AddAppUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addAppUserToGroup, arg.GroupID, arg.AppUserID)
	return err
}

const appAccessVersion = `-- name: AppAccessVersion :one
SELECT COALESCE(EXTRACT(EPOCH FROM GREATEST(
    (SELECT MAX(g.created_at) FROM app_grants g WHERE g.organisation_id = $1),
    (SELECT MAX(r.updated_at) FROM app_roles r WHERE r.organisation_id = $1),
    (SELECT MAX(m.created_at) FROM app_user_group_members m WHERE m.app_user_id = $2)
))::bigint, 0)::bigint AS version
`

type AppAccessVersionParams struct {
	OrganisationID string `json:"organisation_id"`
	AppUserID      string `json:"app_user_id"`
}

// AppAccessVersion changes whenever anything a customer's grant set depends on
// changes, so a merchant can cache by version instead of polling.
// AppAccessVersion changes whenever anything a customer's grant set depends on
// changes, so a merchant can cache by version instead of polling.
//
// Grants are taken organisation-wide rather than per user, because a grant made
// to a group affects members without touching their rows. Over-invalidating is
// the safe direction: a stale cache silently serves the wrong permissions.
func (q *Queries) AppAccessVersion(ctx context.Context, arg AppAccessVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, appAccessVersion, arg.OrganisationID, arg.AppUserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createAppCapability = `-- name: CreateAppCapability :one
INSERT INTO app_capabilities (id, organisation_id, key, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, key, description, created_at
`

type CreateAppCapabilityParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Description    string `json:"description"`
}

func (q *Queries) CreateAppCapability(ctx context.Context, arg CreateAppCapabilityParams) (AppCapability, error) {
	row := q.db.QueryRow(ctx, createAppCapability,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Description,
	)
	var i AppCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createAppEveryoneGrant = `-- name: CreateAppEveryoneGrant :one
INSERT INTO app_grants (
    id, organisation_id, subject_kind, role_id, scope_kind, scope_id,
    expires_at, granted_by, all_capabilities, except_capabilities, except_scopes,
    except_app_user_ids, constraint_kind
) VALUES ($1, $2, 'everyone', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (organisation_id, COALESCE(role_id, ''), scope_kind, scope_id) WHERE subject_kind = 'everyone'
DO UPDATE SET expires_at = EXCLUDED.expires_at, granted_by = EXCLUDED.granted_by,
    except_capabilities = EXCLUDED.except_capabilities, except_scopes = EXCLUDED.except_scopes,
    except_app_user_ids = EXCLUDED.except_app_user_ids, constraint_kind = EXCLUDED.constraint_kind
RETURNING id, organisation_id, app_user_id, role_id, scope_kind, scope_id, expires_at, granted_by, created_at, group_id, subject_kind, except_app_user_ids, except_scopes, all_capabilities, except_capabilities, constraint_kind
`

type CreateAppEveryoneGrantParams struct {
	ID                 string             `json:"id"`
	OrganisationID     string             `json:"organisation_id"`
	RoleID             pgtype.Text        `json:"role_id"`
	ScopeKind          string             `json:"scope_kind"`
	ScopeID            string             `json:"scope_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	GrantedBy          string             `json:"granted_by"`
	AllCapabilities    bool               `json:"all_capabilities"`
	ExceptCapabilities []string           `json:"except_capabilities"`
	ExceptScopes       json.RawMessage    `json:"except_scopes"`
	ExceptAppUserIds   []string           `json:"except_app_user_ids"`
	ConstraintKind     string             `json:"constraint_kind"`
}

// CreateAppEveryoneGrant covers every customer of the organisation, present and
// future, from one row. It names no subject because it names all of them.
func (q *Queries) CreateAppEveryoneGrant(ctx context.Context, arg CreateAppEveryoneGrantParams) (AppGrant, error) {
	row := q.db.QueryRow(ctx, createAppEveryoneGrant,
		arg.ID,
		arg.OrganisationID,
		arg.RoleID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.GrantedBy,
		arg.AllCapabilities,
		arg.ExceptCapabilities,
		arg.ExceptScopes,
		arg.ExceptAppUserIds,
		arg.ConstraintKind,
	)
	var i AppGrant
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.AppUserID,
		&i.RoleID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.GroupID,
		&i.SubjectKind,
		&i.ExceptAppUserIds,
		&i.ExceptScopes,
		&i.AllCapabilities,
		&i.ExceptCapabilities,
		&i.ConstraintKind,
	)
	return i, err
}

const createAppGroupGrant = `-- name: CreateAppGroupGrant :one
INSERT INTO app_grants (
    id, organisation_id, subject_kind, group_id, role_id, scope_kind, scope_id,
    expires_at, granted_by, all_capabilities, except_capabilities, except_scopes,
    except_app_user_ids, constraint_kind
) VALUES ($1, $2, 'group', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (group_id, COALESCE(role_id, ''), scope_kind, scope_id) WHERE group_id IS NOT NULL
DO UPDATE SET expires_at = EXCLUDED.expires_at, granted_by = EXCLUDED.granted_by,
    except_capabilities = EXCLUDED.except_capabilities, except_scopes = EXCLUDED.except_scopes,
    except_app_user_ids = EXCLUDED.except_app_user_ids, constraint_kind = EXCLUDED.constraint_kind
RETURNING id, organisation_id, app_user_id, role_id, scope_kind, scope_id, expires_at, granted_by, created_at, group_id, subject_kind, except_app_user_ids, except_scopes, all_capabilities, except_capabilities, constraint_kind
`

type CreateAppGroupGrantParams struct {
	ID                 string             `json:"id"`
	OrganisationID     string             `json:"organisation_id"`
	GroupID            pgtype.Text        `json:"group_id"`
	RoleID             pgtype.Text        `json:"role_id"`
	ScopeKind          string             `json:"scope_kind"`
	ScopeID            string             `json:"scope_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	GrantedBy          string             `json:"granted_by"`
	AllCapabilities    bool               `json:"all_capabilities"`
	ExceptCapabilities []string           `json:"except_capabilities"`
	ExceptScopes       json.RawMessage    `json:"except_scopes"`
	ExceptAppUserIds   []string           `json:"except_app_user_ids"`
	ConstraintKind     string             `json:"constraint_kind"`
}

func (q *Queries) CreateAppGroupGrant(ctx context.Context, arg CreateAppGroupGrantParams) (AppGrant, error) {
	row := q.db.QueryRow(ctx, createAppGroupGrant,
		arg.ID,
		arg.OrganisationID,
		arg.GroupID,
		arg.RoleID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.GrantedBy,
		arg.AllCapabilities,
		arg.ExceptCapabilities,
		arg.ExceptScopes,
		arg.ExceptAppUserIds,
		arg.ConstraintKind,
	)
	var i AppGrant
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.AppUserID,
		&i.RoleID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.GroupID,
		&i.SubjectKind,
		&i.ExceptAppUserIds,
		&i.ExceptScopes,
		&i.AllCapabilities,
		&i.ExceptCapabilities,
		&i.ConstraintKind,
	)
	return i, err
}

const createAppRole = `-- name: CreateAppRole :one
INSERT INTO app_roles (id, organisation_id, key, name, description, own_capabilities)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at
`

type CreateAppRoleParams struct {
	ID              string   `json:"id"`
	OrganisationID  string   `json:"organisation_id"`
	Key             string   `json:"key"`
	Name            string   `json:"name"`
	Description     string   `json:"description"`
	OwnCapabilities []string `json:"own_capabilities"`
}

func (q *Queries) CreateAppRole(ctx context.Context, arg CreateAppRoleParams) (AppRole, error) {
	row := q.db.QueryRow(ctx, createAppRole,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.OwnCapabilities,
	)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppScopeType = `-- name: CreateAppScopeType :one
INSERT INTO app_scope_types (id, organisation_id, kind, label)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, kind, label, created_at
`

type CreateAppScopeTypeParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Kind           string `json:"kind"`
	Label          string `json:"label"`
}

func (q *Queries) CreateAppScopeType(ctx context.Context, arg CreateAppScopeTypeParams) (AppScopeType, error) {
	row := q.db.QueryRow(ctx, createAppScopeType,
		arg.ID,
		arg.OrganisationID,
		arg.Kind,
		arg.Label,
	)
	var i AppScopeType
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const createAppUserGrant = `-- name: CreateAppUserGrant :one

INSERT INTO app_grants (
    id, organisation_id, subject_kind, app_user_id, role_id, scope_kind, scope_id,
    expires_at, granted_by, all_capabilities, except_capabilities, except_scopes,
    except_app_user_ids, constraint_kind
) VALUES ($1, $2, 'app_user', $3, $4, $5, $6, $7, $8, $9, $10, $11, '{}', $12)
ON CONFLICT (app_user_id, COALESCE(role_id, ''), scope_kind, scope_id) WHERE app_user_id IS NOT NULL
DO UPDATE SET expires_at = EXCLUDED.expires_at, granted_by = EXCLUDED.granted_by,
    except_capabilities = EXCLUDED.except_capabilities, except_scopes = EXCLUDED.except_scopes,
    constraint_kind = EXCLUDED.constraint_kind
RETURNING id, organisation_id, app_user_id, role_id, scope_kind, scope_id, expires_at, granted_by, created_at, group_id, subject_kind, except_app_user_ids, except_scopes, all_capabilities, except_capabilities, constraint_kind
`

type CreateAppUserGrantParams struct {
	ID                 string             `json:"id"`
	OrganisationID     string             `json:"organisation_id"`
	AppUserID          pgtype.Text        `json:"app_user_id"`
	RoleID             pgtype.Text        `json:"role_id"`
	ScopeKind          string             `json:"scope_kind"`
	ScopeID            string             `json:"scope_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	GrantedBy          string             `json:"granted_by"`
	AllCapabilities    bool               `json:"all_capabilities"`
	ExceptCapabilities []string           `json:"except_capabilities"`
	ExceptScopes       json.RawMessage    `json:"except_scopes"`
	ConstraintKind     string             `json:"constraint_kind"`
}

// Three inserts rather than one, because each subject kind conflicts against a
// different partial index and a statement may name only one.
//
// The upsert keeps re-granting idempotent: issuing the same role at the same
// scope refreshes the expiry and the exceptions rather than failing.
func (q *Queries) CreateAppUserGrant(ctx context.Context, arg CreateAppUserGrantParams) (AppGrant, error) {
	row := q.db.QueryRow(ctx, createAppUserGrant,
		arg.ID,
		arg.OrganisationID,
		arg.AppUserID,
		arg.RoleID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.GrantedBy,
		arg.AllCapabilities,
		arg.ExceptCapabilities,
		arg.ExceptScopes,
		arg.ConstraintKind,
	)
	var i AppGrant
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.AppUserID,
		&i.RoleID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.GroupID,
		&i.SubjectKind,
		&i.ExceptAppUserIds,
		&i.ExceptScopes,
		&i.AllCapabilities,
		&i.ExceptCapabilities,
		&i.ConstraintKind,
	)
	return i, err
}

const createAppUserGroup = `-- name: CreateAppUserGroup :one
INSERT INTO app_user_groups (id, organisation_id, key, name, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, key, name, description, created_at, updated_at
`

type CreateAppUserGroupParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
}

func (q *Queries) CreateAppUserGroup(ctx context.Context, arg CreateAppUserGroupParams) (AppUserGroup, error) {
	row := q.db.QueryRow(ctx, createAppUserGroup,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
	)
	var i AppUserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppCapability = `-- name: DeleteAppCapability :exec
DELETE FROM app_capabilities WHERE id = $1 AND organisation_id = $2
`

type DeleteAppCapabilityParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppCapability(ctx context.Context, arg DeleteAppCapabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAppCapability, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppGrant = `-- name: DeleteAppGrant :exec
DELETE FROM app_grants WHERE id = $1 AND organisation_id = $2
`

type DeleteAppGrantParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppGrant(ctx context.Context, arg DeleteAppGrantParams) error {
	_, err := q.db.Exec(ctx, deleteAppGrant, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppRole = `-- name: DeleteAppRole :exec
DELETE FROM app_roles WHERE id = $1 AND organisation_id = $2
`

type DeleteAppRoleParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppRole(ctx context.Context, arg DeleteAppRoleParams) error {
	_, err := q.db.Exec(ctx, deleteAppRole, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppScopeType = `-- name: DeleteAppScopeType :exec
DELETE FROM app_scope_types WHERE id = $1 AND organisation_id = $2
`

type DeleteAppScopeTypeParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppScopeType(ctx context.Context, arg DeleteAppScopeTypeParams) error {
	_, err := q.db.Exec(ctx, deleteAppScopeType, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppUserGroup = `-- name: DeleteAppUserGroup :exec
DELETE FROM app_user_groups WHERE id = $1 AND organisation_id = $2
`

type DeleteAppUserGroupParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppUserGroup(ctx context.Context, arg DeleteAppUserGroupParams) error {
	_, err := q.db.Exec(ctx, deleteAppUserGroup, arg.ID, arg.OrganisationID)
	return err
}

const getAppCapability = `-- name: GetAppCapability :one
SELECT id, organisation_id, key, description, created_at FROM app_capabilities WHERE id = $1
`

func (q *Queries) GetAppCapability(ctx context.Context, id string) (AppCapability, error) {
	row := q.db.QueryRow(ctx, getAppCapability, id)
	var i AppCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAppRole = `-- name: GetAppRole :one
SELECT id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at FROM app_roles WHERE id = $1
`

func (q *Queries) GetAppRole(ctx context.Context, id string) (AppRole, error) {
	row := q.db.QueryRow(ctx, getAppRole, id)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppScopeType = `-- name: GetAppScopeType :one
SELECT id, organisation_id, kind, label, created_at FROM app_scope_types WHERE id = $1
`

func (q *Queries) GetAppScopeType(ctx context.Context, id string) (AppScopeType, error) {
	row := q.db.QueryRow(ctx, getAppScopeType, id)
	var i AppScopeType
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getAppUserGroup = `-- name: GetAppUserGroup :one
SELECT id, organisation_id, key, name, description, created_at, updated_at FROM app_user_groups WHERE id = $1
`

func (q *Queries) GetAppUserGroup(ctx context.Context, id string) (AppUserGroup, error) {
	row := q.db.QueryRow(ctx, getAppUserGroup, id)
	var i AppUserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppCapabilities = `-- name: ListAppCapabilities :many
SELECT id, organisation_id, key, description, created_at FROM app_capabilities
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListAppCapabilities(ctx context.Context, organisationID string) ([]AppCapability, error) {
	rows, err := q.db.Query(ctx, listAppCapabilities, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCapability{}
	for rows.Next() {
		var i AppCapability
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppGrantsForOrg = `-- name: ListAppGrantsForOrg :many
SELECT g.id, g.scope_kind, g.scope_id, g.expires_at, g.app_user_id, g.group_id,
       COALESCE(r.key, '')::text AS role_key, COALESCE(grp.key, '')::text AS group_key,
       COALESCE(u.email, '')::text AS app_user_email, g.subject_kind,
       g.all_capabilities, g.except_capabilities, g.except_scopes,
       g.except_app_user_ids, g.constraint_kind
FROM app_grants g
LEFT JOIN app_roles r ON r.id = g.role_id
LEFT JOIN app_user_groups grp ON grp.id = g.group_id
LEFT JOIN app_users u ON u.id = g.app_user_id
WHERE g.organisation_id = $1
ORDER BY g.created_at DESC
LIMIT $2
`

type ListAppGrantsForOrgParams struct {
	OrganisationID string `json:"organisation_id"`
	Limit          int32  `json:"limit"`
}

type ListAppGrantsForOrgRow struct {
	ID                 string             `json:"id"`
	ScopeKind          string             `json:"scope_kind"`
	ScopeID            string             `json:"scope_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	AppUserID          pgtype.Text        `json:"app_user_id"`
	GroupID            pgtype.Text        `json:"group_id"`
	RoleKey            string             `json:"role_key"`
	GroupKey           string             `json:"group_key"`
	AppUserEmail       string             `json:"app_user_email"`
	SubjectKind        string             `json:"subject_kind"`
	AllCapabilities    bool               `json:"all_capabilities"`
	ExceptCapabilities []string           `json:"except_capabilities"`
	ExceptScopes       json.RawMessage    `json:"except_scopes"`
	ExceptAppUserIds   []string           `json:"except_app_user_ids"`
	ConstraintKind     string             `json:"constraint_kind"`
}

func (q *Queries) ListAppGrantsForOrg(ctx context.Context, arg ListAppGrantsForOrgParams) ([]ListAppGrantsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listAppGrantsForOrg, arg.OrganisationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppGrantsForOrgRow{}
	for rows.Next() {
		var i ListAppGrantsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.AppUserID,
			&i.GroupID,
			&i.RoleKey,
			&i.GroupKey,
			&i.AppUserEmail,
			&i.SubjectKind,
			&i.AllCapabilities,
			&i.ExceptCapabilities,
			&i.ExceptScopes,
			&i.ExceptAppUserIds,
			&i.ConstraintKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppGrantsForUser = `-- name: ListAppGrantsForUser :many
SELECT g.id, g.scope_kind, g.scope_id, g.expires_at, g.role_id,
       COALESCE(r.key, '')::text AS role_key,
       COALESCE(r.effective_capabilities, '{}')::text[] AS effective_capabilities,
       g.group_id, ''::text AS group_key, 'app_user'::text AS subject_kind,
       g.all_capabilities, g.except_capabilities, g.except_scopes, g.constraint_kind
FROM app_grants g
LEFT JOIN app_roles r ON r.id = g.role_id
WHERE g.app_user_id = $1
  AND (g.expires_at IS NULL OR g.expires_at > now())
UNION ALL
SELECT g.id, g.scope_kind, g.scope_id, g.expires_at, g.role_id,
       COALESCE(r.key, '')::text AS role_key,
       COALESCE(r.effective_capabilities, '{}')::text[] AS effective_capabilities,
       g.group_id, grp.key AS group_key, 'group'::text AS subject_kind,
       g.all_capabilities, g.except_capabilities, g.except_scopes, g.constraint_kind
FROM app_user_group_members m
JOIN app_grants g ON g.group_id = m.group_id
LEFT JOIN app_roles r ON r.id = g.role_id
JOIN app_user_groups grp ON grp.id = g.group_id
WHERE m.app_user_id = $1
  AND (g.expires_at IS NULL OR g.expires_at > now())
  AND NOT ($1::text = ANY (g.except_app_user_ids))
UNION ALL
SELECT g.id, g.scope_kind, g.scope_id, g.expires_at, g.role_id,
       COALESCE(r.key, '')::text AS role_key,
       COALESCE(r.effective_capabilities, '{}')::text[] AS effective_capabilities,
       g.group_id, ''::text AS group_key, 'everyone'::text AS subject_kind,
       g.all_capabilities, g.except_capabilities, g.except_scopes, g.constraint_kind
FROM app_grants g
LEFT JOIN app_roles r ON r.id = g.role_id
WHERE g.organisation_id = $2
  AND g.subject_kind = 'everyone'
  AND (g.expires_at IS NULL OR g.expires_at > now())
  AND NOT ($1::text = ANY (g.except_app_user_ids))
`

type ListAppGrantsForUserParams struct {
	AppUserID      pgtype.Text `json:"app_user_id"`
	OrganisationID string      `json:"organisation_id"`
}

type ListAppGrantsForUserRow struct {
	ID                    string             `json:"id"`
	ScopeKind             string             `json:"scope_kind"`
	ScopeID               string             `json:"scope_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RoleID                pgtype.Text        `json:"role_id"`
	RoleKey               string             `json:"role_key"`
	EffectiveCapabilities []string           `json:"effective_capabilities"`
	GroupID               pgtype.Text        `json:"group_id"`
	GroupKey              string             `json:"group_key"`
	SubjectKind           string             `json:"subject_kind"`
	AllCapabilities       bool               `json:"all_capabilities"`
	ExceptCapabilities    []string           `json:"except_capabilities"`
	ExceptScopes          json.RawMessage    `json:"except_scopes"`
	ConstraintKind        string             `json:"constraint_kind"`
}

// ListAppGrantsForUser returns a customer's live grants with the role's
// materialised capabilities, so the caller never walks the inheritance graph.
//
// Two branches unioned rather than one query with an OR. An OR spanning two
// different access paths — a direct grant and a grant reached through group
// membership — cannot use either index, so Postgres falls back to scanning
// every grant in the table and discarding almost all of them. That cost grows
// with the total across all merchants, on a path a merchant's backend calls
// constantly. Measured at 41k grants: 16.5ms scanning, 0.125ms as a union.
//
// UNION ALL, not UNION: a customer holding the same role at the same scope both
// directly and through a group legitimately has two grants, and the evaluator
// unions capabilities anyway.
// Three branches now. The third carries the organisation's everyone-grants,
// which name no subject and so cannot be reached by either id column.
//
// LEFT JOIN on app_roles rather than JOIN: a wildcard grant carries no role,
// and an inner join would silently drop exactly the grants that grant the most.
//
// except_app_user_ids is applied here rather than in Go so an excluded customer
// never has the row assembled for them at all.
func (q *Queries) ListAppGrantsForUser(ctx context.Context, arg ListAppGrantsForUserParams) ([]ListAppGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAppGrantsForUser, arg.AppUserID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppGrantsForUserRow{}
	for rows.Next() {
		var i ListAppGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.RoleID,
			&i.RoleKey,
			&i.EffectiveCapabilities,
			&i.GroupID,
			&i.GroupKey,
			&i.SubjectKind,
			&i.AllCapabilities,
			&i.ExceptCapabilities,
			&i.ExceptScopes,
			&i.ConstraintKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoleExtends = `-- name: ListAppRoleExtends :many
SELECT e.role_id, e.parent_id
FROM app_role_extends e
JOIN app_roles r ON r.id = e.role_id
WHERE r.organisation_id = $1
`

func (q *Queries) ListAppRoleExtends(ctx context.Context, organisationID string) ([]AppRoleExtend, error) {
	rows, err := q.db.Query(ctx, listAppRoleExtends, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRoleExtend{}
	for rows.Next() {
		var i AppRoleExtend
		if err := rows.Scan(&i.RoleID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoleParents = `-- name: ListAppRoleParents :many
SELECT parent_id FROM app_role_extends WHERE role_id = $1
`

// ListAppRoleParents returns the roles one role builds on, so an edit form can
// show what is already selected.
func (q *Queries) ListAppRoleParents(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAppRoleParents, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_id string
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoles = `-- name: ListAppRoles :many
SELECT id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at FROM app_roles WHERE organisation_id = $1 ORDER BY key
`

func (q *Queries) ListAppRoles(ctx context.Context, organisationID string) ([]AppRole, error) {
	rows, err := q.db.Query(ctx, listAppRoles, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRole{}
	for rows.Next() {
		var i AppRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.OwnCapabilities,
			&i.EffectiveCapabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppScopeTypes = `-- name: ListAppScopeTypes :many
SELECT id, organisation_id, kind, label, created_at FROM app_scope_types
WHERE organisation_id = $1
ORDER BY kind
`

func (q *Queries) ListAppScopeTypes(ctx context.Context, organisationID string) ([]AppScopeType, error) {
	rows, err := q.db.Query(ctx, listAppScopeTypes, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppScopeType{}
	for rows.Next() {
		var i AppScopeType
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Kind,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUserGroupMembers = `-- name: ListAppUserGroupMembers :many
SELECT u.id, u.email, u.display_name, u.status
FROM app_user_group_members m
JOIN app_users u ON u.id = m.app_user_id
WHERE m.group_id = $1
ORDER BY u.email
`

type ListAppUserGroupMembersRow struct {
	ID          string      `json:"id"`
	Email       pgtype.Text `json:"email"`
	DisplayName string      `json:"display_name"`
	Status      string      `json:"status"`
}

func (q *Queries) ListAppUserGroupMembers(ctx context.Context, groupID string) ([]ListAppUserGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listAppUserGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppUserGroupMembersRow{}
	for rows.Next() {
		var i ListAppUserGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUserGroups = `-- name: ListAppUserGroups :many
SELECT g.id, g.organisation_id, g.key, g.name, g.description, g.created_at, g.updated_at, (SELECT COUNT(*) FROM app_user_group_members m WHERE m.group_id = g.id)::bigint AS member_count
FROM app_user_groups g
WHERE g.organisation_id = $1
ORDER BY g.key
`

type ListAppUserGroupsRow struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	Key            string    `json:"key"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	MemberCount    int64     `json:"member_count"`
}

func (q *Queries) ListAppUserGroups(ctx context.Context, organisationID string) ([]ListAppUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAppUserGroups, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppUserGroupsRow{}
	for rows.Next() {
		var i ListAppUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForAppUser = `-- name: ListGroupsForAppUser :many
SELECT g.id, g.key, g.name
FROM app_user_group_members m
JOIN app_user_groups g ON g.id = m.group_id
WHERE m.app_user_id = $1
ORDER BY g.key
`

type ListGroupsForAppUserRow struct {
	ID   string `json:"id"`
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (q *Queries) ListGroupsForAppUser(ctx context.Context, appUserID string) ([]ListGroupsForAppUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForAppUser, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForAppUserRow{}
	for rows.Next() {
		var i ListGroupsForAppUserRow
		if err := rows.Scan(&i.ID, &i.Key, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAppUserFromGroup = `-- name: RemoveAppUserFromGroup :exec
DELETE FROM app_user_group_members WHERE group_id = $1 AND app_user_id = $2
`

type RemoveAppUserFromGroupParams struct {
	GroupID   string `json:"group_id"`
	AppUserID string `json:"app_user_id"`
}

func (q *Queries) RemoveAppUserFromGroup(ctx context.Context, arg RemoveAppUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeAppUserFromGroup, arg.GroupID, arg.AppUserID)
	return err
}

const replaceAppRoleExtends = `-- name: ReplaceAppRoleExtends :exec
DELETE FROM app_role_extends WHERE role_id = $1
`

func (q *Queries) ReplaceAppRoleExtends(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, replaceAppRoleExtends, roleID)
	return err
}

const setAppRoleEffectiveCapabilities = `-- name: SetAppRoleEffectiveCapabilities :exec
UPDATE app_roles SET effective_capabilities = $2, updated_at = now() WHERE id = $1
`

type SetAppRoleEffectiveCapabilitiesParams struct {
	ID                    string   `json:"id"`
	EffectiveCapabilities []string `json:"effective_capabilities"`
}

func (q *Queries) SetAppRoleEffectiveCapabilities(ctx context.Context, arg SetAppRoleEffectiveCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setAppRoleEffectiveCapabilities, arg.ID, arg.EffectiveCapabilities)
	return err
}

const updateAppCapability = `-- name: UpdateAppCapability :one
UPDATE app_capabilities
SET description = COALESCE($1, description)
WHERE id = $2 AND organisation_id = $3
RETURNING id, organisation_id, key, description, created_at
`

type UpdateAppCapabilityParams struct {
	Description    pgtype.Text `json:"description"`
	ID             string      `json:"id"`
	OrganisationID string      `json:"organisation_id"`
}

func (q *Queries) UpdateAppCapability(ctx context.Context, arg UpdateAppCapabilityParams) (AppCapability, error) {
	row := q.db.QueryRow(ctx, updateAppCapability, arg.Description, arg.ID, arg.OrganisationID)
	var i AppCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateAppRole = `-- name: UpdateAppRole :one
UPDATE app_roles
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    own_capabilities = COALESCE($3, own_capabilities),
    updated_at = now()
WHERE id = $4 AND organisation_id = $5
RETURNING id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at
`

type UpdateAppRoleParams struct {
	Name            pgtype.Text `json:"name"`
	Description     pgtype.Text `json:"description"`
	OwnCapabilities []string    `json:"own_capabilities"`
	ID              string      `json:"id"`
	OrganisationID  string      `json:"organisation_id"`
}

func (q *Queries) UpdateAppRole(ctx context.Context, arg UpdateAppRoleParams) (AppRole, error) {
	row := q.db.QueryRow(ctx, updateAppRole,
		arg.Name,
		arg.Description,
		arg.OwnCapabilities,
		arg.ID,
		arg.OrganisationID,
	)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppScopeType = `-- name: UpdateAppScopeType :one
UPDATE app_scope_types
SET label = COALESCE($1, label)
WHERE id = $2 AND organisation_id = $3
RETURNING id, organisation_id, kind, label, created_at
`

type UpdateAppScopeTypeParams struct {
	Label          pgtype.Text `json:"label"`
	ID             string      `json:"id"`
	OrganisationID string      `json:"organisation_id"`
}

func (q *Queries) UpdateAppScopeType(ctx context.Context, arg UpdateAppScopeTypeParams) (AppScopeType, error) {
	row := q.db.QueryRow(ctx, updateAppScopeType, arg.Label, arg.ID, arg.OrganisationID)
	var i AppScopeType
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const updateAppUserGroup = `-- name: UpdateAppUserGroup :one
UPDATE app_user_groups
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = now()
WHERE id = $3 AND organisation_id = $4
RETURNING id, organisation_id, key, name, description, created_at, updated_at
`

type UpdateAppUserGroupParams struct {
	Name           pgtype.Text `json:"name"`
	Description    pgtype.Text `json:"description"`
	ID             string      `json:"id"`
	OrganisationID string      `json:"organisation_id"`
}

func (q *Queries) UpdateAppUserGroup(ctx context.Context, arg UpdateAppUserGroupParams) (AppUserGroup, error) {
	row := q.db.QueryRow(ctx, updateAppUserGroup,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.OrganisationID,
	)
	var i AppUserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
