// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_users.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_users (
    id, organisation_id, external_id, email, display_name, status, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organisation_id, external_id, email, display_name, status, attributes, created_at, updated_at
`

type CreateAppUserParams struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	ExternalID     pgtype.Text     `json:"external_id"`
	Email          pgtype.Text     `json:"email"`
	DisplayName    string          `json:"display_name"`
	Status         string          `json:"status"`
	Attributes     json.RawMessage `json:"attributes"`
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.ID,
		arg.OrganisationID,
		arg.ExternalID,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.Attributes,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttributeDefinition = `-- name: CreateAttributeDefinition :one
INSERT INTO attribute_definitions (
    id, organisation_id, key, label, description, value_type,
    section, sort_order, required, enum_values, is_pii, status
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING id, organisation_id, key, label, description, value_type, section, sort_order, required, enum_values, is_pii, status, created_at, updated_at
`

type CreateAttributeDefinitionParams struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	Key            string          `json:"key"`
	Label          string          `json:"label"`
	Description    string          `json:"description"`
	ValueType      string          `json:"value_type"`
	Section        string          `json:"section"`
	SortOrder      int32           `json:"sort_order"`
	Required       bool            `json:"required"`
	EnumValues     json.RawMessage `json:"enum_values"`
	IsPii          bool            `json:"is_pii"`
	Status         string          `json:"status"`
}

func (q *Queries) CreateAttributeDefinition(ctx context.Context, arg CreateAttributeDefinitionParams) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, createAttributeDefinition,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.ValueType,
		arg.Section,
		arg.SortOrder,
		arg.Required,
		arg.EnumValues,
		arg.IsPii,
		arg.Status,
	)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.ValueType,
		&i.Section,
		&i.SortOrder,
		&i.Required,
		&i.EnumValues,
		&i.IsPii,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppUser = `-- name: GetAppUser :one
SELECT id, organisation_id, external_id, email, display_name, status, attributes, created_at, updated_at FROM app_users WHERE id = $1
`

func (q *Queries) GetAppUser(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeDefinition = `-- name: GetAttributeDefinition :one
SELECT id, organisation_id, key, label, description, value_type, section, sort_order, required, enum_values, is_pii, status, created_at, updated_at FROM attribute_definitions WHERE id = $1
`

func (q *Queries) GetAttributeDefinition(ctx context.Context, id string) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, getAttributeDefinition, id)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.ValueType,
		&i.Section,
		&i.SortOrder,
		&i.Required,
		&i.EnumValues,
		&i.IsPii,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppUsers = `-- name: ListAppUsers :many
SELECT id, organisation_id, external_id, email, display_name, status, attributes, created_at, updated_at FROM app_users
WHERE organisation_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
`

type ListAppUsersParams struct {
	OrganisationID string      `json:"organisation_id"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) ListAppUsers(ctx context.Context, arg ListAppUsersParams) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listAppUsers, arg.OrganisationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.ExternalID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeDefinitions = `-- name: ListAttributeDefinitions :many
SELECT id, organisation_id, key, label, description, value_type, section, sort_order, required, enum_values, is_pii, status, created_at, updated_at FROM attribute_definitions
WHERE organisation_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY section ASC, sort_order ASC, key ASC
`

type ListAttributeDefinitionsParams struct {
	OrganisationID string      `json:"organisation_id"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) ListAttributeDefinitions(ctx context.Context, arg ListAttributeDefinitionsParams) ([]AttributeDefinition, error) {
	rows, err := q.db.Query(ctx, listAttributeDefinitions, arg.OrganisationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeDefinition{}
	for rows.Next() {
		var i AttributeDefinition
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Label,
			&i.Description,
			&i.ValueType,
			&i.Section,
			&i.SortOrder,
			&i.Required,
			&i.EnumValues,
			&i.IsPii,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppUser = `-- name: UpdateAppUser :one
UPDATE app_users SET
    external_id = COALESCE($2, external_id),
    email = COALESCE($3, email),
    display_name = COALESCE($4, display_name),
    status = COALESCE($5, status),
    attributes = COALESCE($6, attributes),
    updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, external_id, email, display_name, status, attributes, created_at, updated_at
`

type UpdateAppUserParams struct {
	ID          string      `json:"id"`
	ExternalID  pgtype.Text `json:"external_id"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	Status      pgtype.Text `json:"status"`
	Attributes  []byte      `json:"attributes"`
}

func (q *Queries) UpdateAppUser(ctx context.Context, arg UpdateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateAppUser,
		arg.ID,
		arg.ExternalID,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.Attributes,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttributeDefinition = `-- name: UpdateAttributeDefinition :one
UPDATE attribute_definitions SET
    label = COALESCE($2, label),
    description = COALESCE($3, description),
    value_type = COALESCE($4, value_type),
    section = COALESCE($5, section),
    sort_order = COALESCE($6, sort_order),
    required = COALESCE($7, required),
    enum_values = COALESCE($8, enum_values),
    is_pii = COALESCE($9, is_pii),
    status = COALESCE($10, status),
    updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, key, label, description, value_type, section, sort_order, required, enum_values, is_pii, status, created_at, updated_at
`

type UpdateAttributeDefinitionParams struct {
	ID          string      `json:"id"`
	Label       pgtype.Text `json:"label"`
	Description pgtype.Text `json:"description"`
	ValueType   pgtype.Text `json:"value_type"`
	Section     pgtype.Text `json:"section"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
	Required    pgtype.Bool `json:"required"`
	EnumValues  []byte      `json:"enum_values"`
	IsPii       pgtype.Bool `json:"is_pii"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdateAttributeDefinition(ctx context.Context, arg UpdateAttributeDefinitionParams) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, updateAttributeDefinition,
		arg.ID,
		arg.Label,
		arg.Description,
		arg.ValueType,
		arg.Section,
		arg.SortOrder,
		arg.Required,
		arg.EnumValues,
		arg.IsPii,
		arg.Status,
	)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.ValueType,
		&i.Section,
		&i.SortOrder,
		&i.Required,
		&i.EnumValues,
		&i.IsPii,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
