// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAppRoleExtends = `-- name: AddAppRoleExtends :exec
INSERT INTO app_role_extends (role_id, parent_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAppRoleExtendsParams struct {
	RoleID   string `json:"role_id"`
	ParentID string `json:"parent_id"`
}

func (q *Queries) AddAppRoleExtends(ctx context.Context, arg AddAppRoleExtendsParams) error {
	_, err := q.db.Exec(ctx, addAppRoleExtends, arg.RoleID, arg.ParentID)
	return err
}

const appAccessVersion = `-- name: AppAccessVersion :one
SELECT COALESCE(EXTRACT(EPOCH FROM GREATEST(
    (SELECT MAX(g.created_at) FROM app_grants g WHERE g.app_user_id = $1),
    (SELECT MAX(r.updated_at) FROM app_roles r WHERE r.organisation_id = $2)
))::bigint, 0)::bigint AS version
`

type AppAccessVersionParams struct {
	AppUserID      string `json:"app_user_id"`
	OrganisationID string `json:"organisation_id"`
}

// AppAccessVersion changes whenever anything a customer's grant set depends on
// changes, so a merchant can cache by version instead of polling.
func (q *Queries) AppAccessVersion(ctx context.Context, arg AppAccessVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, appAccessVersion, arg.AppUserID, arg.OrganisationID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createAppCapability = `-- name: CreateAppCapability :one
INSERT INTO app_capabilities (id, organisation_id, key, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, key, description, created_at
`

type CreateAppCapabilityParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Description    string `json:"description"`
}

func (q *Queries) CreateAppCapability(ctx context.Context, arg CreateAppCapabilityParams) (AppCapability, error) {
	row := q.db.QueryRow(ctx, createAppCapability,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Description,
	)
	var i AppCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createAppGrant = `-- name: CreateAppGrant :one
INSERT INTO app_grants (id, organisation_id, app_user_id, role_id, scope_kind, scope_id, expires_at, granted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (app_user_id, role_id, scope_kind, scope_id)
DO UPDATE SET expires_at = EXCLUDED.expires_at, granted_by = EXCLUDED.granted_by
RETURNING id, organisation_id, app_user_id, role_id, scope_kind, scope_id, expires_at, granted_by, created_at
`

type CreateAppGrantParams struct {
	ID             string             `json:"id"`
	OrganisationID string             `json:"organisation_id"`
	AppUserID      string             `json:"app_user_id"`
	RoleID         string             `json:"role_id"`
	ScopeKind      string             `json:"scope_kind"`
	ScopeID        string             `json:"scope_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	GrantedBy      string             `json:"granted_by"`
}

func (q *Queries) CreateAppGrant(ctx context.Context, arg CreateAppGrantParams) (AppGrant, error) {
	row := q.db.QueryRow(ctx, createAppGrant,
		arg.ID,
		arg.OrganisationID,
		arg.AppUserID,
		arg.RoleID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ExpiresAt,
		arg.GrantedBy,
	)
	var i AppGrant
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.AppUserID,
		&i.RoleID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAppRole = `-- name: CreateAppRole :one
INSERT INTO app_roles (id, organisation_id, key, name, description, own_capabilities)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at
`

type CreateAppRoleParams struct {
	ID              string   `json:"id"`
	OrganisationID  string   `json:"organisation_id"`
	Key             string   `json:"key"`
	Name            string   `json:"name"`
	Description     string   `json:"description"`
	OwnCapabilities []string `json:"own_capabilities"`
}

func (q *Queries) CreateAppRole(ctx context.Context, arg CreateAppRoleParams) (AppRole, error) {
	row := q.db.QueryRow(ctx, createAppRole,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.OwnCapabilities,
	)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppScopeType = `-- name: CreateAppScopeType :one
INSERT INTO app_scope_types (id, organisation_id, kind, label)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, kind, label, created_at
`

type CreateAppScopeTypeParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Kind           string `json:"kind"`
	Label          string `json:"label"`
}

func (q *Queries) CreateAppScopeType(ctx context.Context, arg CreateAppScopeTypeParams) (AppScopeType, error) {
	row := q.db.QueryRow(ctx, createAppScopeType,
		arg.ID,
		arg.OrganisationID,
		arg.Kind,
		arg.Label,
	)
	var i AppScopeType
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppCapability = `-- name: DeleteAppCapability :exec
DELETE FROM app_capabilities WHERE id = $1 AND organisation_id = $2
`

type DeleteAppCapabilityParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppCapability(ctx context.Context, arg DeleteAppCapabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAppCapability, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppGrant = `-- name: DeleteAppGrant :exec
DELETE FROM app_grants WHERE id = $1 AND organisation_id = $2
`

type DeleteAppGrantParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppGrant(ctx context.Context, arg DeleteAppGrantParams) error {
	_, err := q.db.Exec(ctx, deleteAppGrant, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppRole = `-- name: DeleteAppRole :exec
DELETE FROM app_roles WHERE id = $1 AND organisation_id = $2
`

type DeleteAppRoleParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppRole(ctx context.Context, arg DeleteAppRoleParams) error {
	_, err := q.db.Exec(ctx, deleteAppRole, arg.ID, arg.OrganisationID)
	return err
}

const deleteAppScopeType = `-- name: DeleteAppScopeType :exec
DELETE FROM app_scope_types WHERE id = $1 AND organisation_id = $2
`

type DeleteAppScopeTypeParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteAppScopeType(ctx context.Context, arg DeleteAppScopeTypeParams) error {
	_, err := q.db.Exec(ctx, deleteAppScopeType, arg.ID, arg.OrganisationID)
	return err
}

const getAppRole = `-- name: GetAppRole :one
SELECT id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at FROM app_roles WHERE id = $1
`

func (q *Queries) GetAppRole(ctx context.Context, id string) (AppRole, error) {
	row := q.db.QueryRow(ctx, getAppRole, id)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppCapabilities = `-- name: ListAppCapabilities :many
SELECT id, organisation_id, key, description, created_at FROM app_capabilities
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListAppCapabilities(ctx context.Context, organisationID string) ([]AppCapability, error) {
	rows, err := q.db.Query(ctx, listAppCapabilities, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCapability{}
	for rows.Next() {
		var i AppCapability
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppGrantsForUser = `-- name: ListAppGrantsForUser :many
SELECT g.id, g.scope_kind, g.scope_id, g.expires_at, g.role_id,
       r.key AS role_key, r.effective_capabilities
FROM app_grants g
JOIN app_roles r ON r.id = g.role_id
WHERE g.app_user_id = $1
  AND (g.expires_at IS NULL OR g.expires_at > now())
ORDER BY g.scope_kind, g.scope_id, r.key
`

type ListAppGrantsForUserRow struct {
	ID                    string             `json:"id"`
	ScopeKind             string             `json:"scope_kind"`
	ScopeID               string             `json:"scope_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RoleID                string             `json:"role_id"`
	RoleKey               string             `json:"role_key"`
	EffectiveCapabilities []string           `json:"effective_capabilities"`
}

// ListAppGrantsForUser returns a customer's live grants with the role's
// materialised capabilities, so the caller never walks the inheritance graph.
func (q *Queries) ListAppGrantsForUser(ctx context.Context, appUserID string) ([]ListAppGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAppGrantsForUser, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppGrantsForUserRow{}
	for rows.Next() {
		var i ListAppGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.ExpiresAt,
			&i.RoleID,
			&i.RoleKey,
			&i.EffectiveCapabilities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoleExtends = `-- name: ListAppRoleExtends :many
SELECT e.role_id, e.parent_id
FROM app_role_extends e
JOIN app_roles r ON r.id = e.role_id
WHERE r.organisation_id = $1
`

func (q *Queries) ListAppRoleExtends(ctx context.Context, organisationID string) ([]AppRoleExtend, error) {
	rows, err := q.db.Query(ctx, listAppRoleExtends, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRoleExtend{}
	for rows.Next() {
		var i AppRoleExtend
		if err := rows.Scan(&i.RoleID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppRoles = `-- name: ListAppRoles :many
SELECT id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at FROM app_roles WHERE organisation_id = $1 ORDER BY key
`

func (q *Queries) ListAppRoles(ctx context.Context, organisationID string) ([]AppRole, error) {
	rows, err := q.db.Query(ctx, listAppRoles, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRole{}
	for rows.Next() {
		var i AppRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.OwnCapabilities,
			&i.EffectiveCapabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppScopeTypes = `-- name: ListAppScopeTypes :many
SELECT id, organisation_id, kind, label, created_at FROM app_scope_types
WHERE organisation_id = $1
ORDER BY kind
`

func (q *Queries) ListAppScopeTypes(ctx context.Context, organisationID string) ([]AppScopeType, error) {
	rows, err := q.db.Query(ctx, listAppScopeTypes, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppScopeType{}
	for rows.Next() {
		var i AppScopeType
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Kind,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAppRoleExtends = `-- name: ReplaceAppRoleExtends :exec
DELETE FROM app_role_extends WHERE role_id = $1
`

func (q *Queries) ReplaceAppRoleExtends(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, replaceAppRoleExtends, roleID)
	return err
}

const setAppRoleEffectiveCapabilities = `-- name: SetAppRoleEffectiveCapabilities :exec
UPDATE app_roles SET effective_capabilities = $2, updated_at = now() WHERE id = $1
`

type SetAppRoleEffectiveCapabilitiesParams struct {
	ID                    string   `json:"id"`
	EffectiveCapabilities []string `json:"effective_capabilities"`
}

func (q *Queries) SetAppRoleEffectiveCapabilities(ctx context.Context, arg SetAppRoleEffectiveCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setAppRoleEffectiveCapabilities, arg.ID, arg.EffectiveCapabilities)
	return err
}

const updateAppRole = `-- name: UpdateAppRole :one
UPDATE app_roles
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    own_capabilities = COALESCE($3, own_capabilities),
    updated_at = now()
WHERE id = $4 AND organisation_id = $5
RETURNING id, organisation_id, key, name, description, own_capabilities, effective_capabilities, created_at, updated_at
`

type UpdateAppRoleParams struct {
	Name            pgtype.Text `json:"name"`
	Description     pgtype.Text `json:"description"`
	OwnCapabilities []string    `json:"own_capabilities"`
	ID              string      `json:"id"`
	OrganisationID  string      `json:"organisation_id"`
}

func (q *Queries) UpdateAppRole(ctx context.Context, arg UpdateAppRoleParams) (AppRole, error) {
	row := q.db.QueryRow(ctx, updateAppRole,
		arg.Name,
		arg.Description,
		arg.OwnCapabilities,
		arg.ID,
		arg.OrganisationID,
	)
	var i AppRole
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.OwnCapabilities,
		&i.EffectiveCapabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
