// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (
    id, organisation_id, name, trigger, enabled, conditions, actions
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organisation_id, name, trigger, enabled, conditions, actions, created_at, updated_at
`

type CreateAutomationParams struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	Name           string          `json:"name"`
	Trigger        string          `json:"trigger"`
	Enabled        bool            `json:"enabled"`
	Conditions     json.RawMessage `json:"conditions"`
	Actions        json.RawMessage `json:"actions"`
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Trigger,
		arg.Enabled,
		arg.Conditions,
		arg.Actions,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Trigger,
		&i.Enabled,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO automation_runs (
    id, organisation_id, automation_id, trigger, status, detail, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organisation_id, automation_id, trigger, status, detail, payload, created_at
`

type CreateAutomationRunParams struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	AutomationID   string          `json:"automation_id"`
	Trigger        string          `json:"trigger"`
	Status         string          `json:"status"`
	Detail         string          `json:"detail"`
	Payload        json.RawMessage `json:"payload"`
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, createAutomationRun,
		arg.ID,
		arg.OrganisationID,
		arg.AutomationID,
		arg.Trigger,
		arg.Status,
		arg.Detail,
		arg.Payload,
	)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.AutomationID,
		&i.Trigger,
		&i.Status,
		&i.Detail,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAutomation = `-- name: DeleteAutomation :exec
DELETE FROM automations WHERE id = $1
`

func (q *Queries) DeleteAutomation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAutomation, id)
	return err
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, organisation_id, name, trigger, enabled, conditions, actions, created_at, updated_at FROM automations WHERE id = $1
`

func (q *Queries) GetAutomation(ctx context.Context, id string) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomation, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Trigger,
		&i.Enabled,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutomationRuns = `-- name: ListAutomationRuns :many
SELECT id, organisation_id, automation_id, trigger, status, detail, payload, created_at FROM automation_runs
WHERE organisation_id = $1
  AND ($2::text IS NULL OR automation_id = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListAutomationRunsParams struct {
	OrganisationID string      `json:"organisation_id"`
	AutomationID   pgtype.Text `json:"automation_id"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListAutomationRuns(ctx context.Context, arg ListAutomationRunsParams) ([]AutomationRun, error) {
	rows, err := q.db.Query(ctx, listAutomationRuns, arg.OrganisationID, arg.AutomationID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRun{}
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.AutomationID,
			&i.Trigger,
			&i.Status,
			&i.Detail,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomations = `-- name: ListAutomations :many
SELECT id, organisation_id, name, trigger, enabled, conditions, actions, created_at, updated_at FROM automations
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAutomations(ctx context.Context, organisationID string) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listAutomations, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Trigger,
			&i.Enabled,
			&i.Conditions,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAutomationsByTrigger = `-- name: ListEnabledAutomationsByTrigger :many
SELECT id, organisation_id, name, trigger, enabled, conditions, actions, created_at, updated_at FROM automations
WHERE organisation_id = $1
  AND trigger = $2
  AND enabled = true
ORDER BY created_at ASC
`

type ListEnabledAutomationsByTriggerParams struct {
	OrganisationID string `json:"organisation_id"`
	Trigger        string `json:"trigger"`
}

func (q *Queries) ListEnabledAutomationsByTrigger(ctx context.Context, arg ListEnabledAutomationsByTriggerParams) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listEnabledAutomationsByTrigger, arg.OrganisationID, arg.Trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Trigger,
			&i.Enabled,
			&i.Conditions,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomation = `-- name: UpdateAutomation :one
UPDATE automations SET
    name = COALESCE($2, name),
    trigger = COALESCE($3, trigger),
    enabled = COALESCE($4, enabled),
    conditions = COALESCE($5, conditions),
    actions = COALESCE($6, actions),
    updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, name, trigger, enabled, conditions, actions, created_at, updated_at
`

type UpdateAutomationParams struct {
	ID         string      `json:"id"`
	Name       pgtype.Text `json:"name"`
	Trigger    pgtype.Text `json:"trigger"`
	Enabled    pgtype.Bool `json:"enabled"`
	Conditions []byte      `json:"conditions"`
	Actions    []byte      `json:"actions"`
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, updateAutomation,
		arg.ID,
		arg.Name,
		arg.Trigger,
		arg.Enabled,
		arg.Conditions,
		arg.Actions,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Trigger,
		&i.Enabled,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
