// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_payments.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePlanPrice = `-- name: GetActivePlanPrice :one
SELECT id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status FROM plan_prices
WHERE plan_id = $1
  AND interval = $2
  AND processor = $3
  AND status = 'active'
`

type GetActivePlanPriceParams struct {
	PlanID    string `json:"plan_id"`
	Interval  string `json:"interval"`
	Processor string `json:"processor"`
}

func (q *Queries) GetActivePlanPrice(ctx context.Context, arg GetActivePlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getActivePlanPrice, arg.PlanID, arg.Interval, arg.Processor)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const getBillingCustomerByOrganisation = `-- name: GetBillingCustomerByOrganisation :one
SELECT id, organisation_id, processor, customer_ref, email, created_at, updated_at FROM billing_customers
WHERE organisation_id = $1
`

func (q *Queries) GetBillingCustomerByOrganisation(ctx context.Context, organisationID string) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, getBillingCustomerByOrganisation, organisationID)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Processor,
		&i.CustomerRef,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingCustomerByProcessorRef = `-- name: GetBillingCustomerByProcessorRef :one
SELECT id, organisation_id, processor, customer_ref, email, created_at, updated_at FROM billing_customers
WHERE processor = $1
  AND customer_ref = $2
`

type GetBillingCustomerByProcessorRefParams struct {
	Processor   string `json:"processor"`
	CustomerRef string `json:"customer_ref"`
}

func (q *Queries) GetBillingCustomerByProcessorRef(ctx context.Context, arg GetBillingCustomerByProcessorRefParams) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, getBillingCustomerByProcessorRef, arg.Processor, arg.CustomerRef)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Processor,
		&i.CustomerRef,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanPrice = `-- name: GetPlanPrice :one
SELECT id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status FROM plan_prices
WHERE id = $1
`

func (q *Queries) GetPlanPrice(ctx context.Context, id string) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getPlanPrice, id)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const getPlanPriceByProcessorRef = `-- name: GetPlanPriceByProcessorRef :one
SELECT id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status FROM plan_prices
WHERE processor = $1
  AND processor_price_ref = $2
`

type GetPlanPriceByProcessorRefParams struct {
	Processor         string `json:"processor"`
	ProcessorPriceRef string `json:"processor_price_ref"`
}

func (q *Queries) GetPlanPriceByProcessorRef(ctx context.Context, arg GetPlanPriceByProcessorRefParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getPlanPriceByProcessorRef, arg.Processor, arg.ProcessorPriceRef)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const getProcessorEvent = `-- name: GetProcessorEvent :one
SELECT id, processor, event_ref, event_type, payload, processed_at, created_at FROM processor_events
WHERE processor = $1
  AND event_ref = $2
`

type GetProcessorEventParams struct {
	Processor string `json:"processor"`
	EventRef  string `json:"event_ref"`
}

func (q *Queries) GetProcessorEvent(ctx context.Context, arg GetProcessorEventParams) (ProcessorEvent, error) {
	row := q.db.QueryRow(ctx, getProcessorEvent, arg.Processor, arg.EventRef)
	var i ProcessorEvent
	err := row.Scan(
		&i.ID,
		&i.Processor,
		&i.EventRef,
		&i.EventType,
		&i.Payload,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByProcessorRef = `-- name: GetSubscriptionByProcessorRef :one
SELECT id, organisation_id, plan_id, status, current_period_end, processor, subscription_ref FROM subscriptions
WHERE processor = $1
  AND subscription_ref = $2
`

type GetSubscriptionByProcessorRefParams struct {
	Processor       pgtype.Text `json:"processor"`
	SubscriptionRef pgtype.Text `json:"subscription_ref"`
}

func (q *Queries) GetSubscriptionByProcessorRef(ctx context.Context, arg GetSubscriptionByProcessorRefParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByProcessorRef, arg.Processor, arg.SubscriptionRef)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.Processor,
		&i.SubscriptionRef,
	)
	return i, err
}

const insertProcessorEvent = `-- name: InsertProcessorEvent :one
INSERT INTO processor_events (id, processor, event_ref, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (processor, event_ref) DO NOTHING
RETURNING id, processor, event_ref, event_type, payload, processed_at, created_at
`

type InsertProcessorEventParams struct {
	ID        string          `json:"id"`
	Processor string          `json:"processor"`
	EventRef  string          `json:"event_ref"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) InsertProcessorEvent(ctx context.Context, arg InsertProcessorEventParams) (ProcessorEvent, error) {
	row := q.db.QueryRow(ctx, insertProcessorEvent,
		arg.ID,
		arg.Processor,
		arg.EventRef,
		arg.EventType,
		arg.Payload,
	)
	var i ProcessorEvent
	err := row.Scan(
		&i.ID,
		&i.Processor,
		&i.EventRef,
		&i.EventType,
		&i.Payload,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanPricesByPlan = `-- name: ListPlanPricesByPlan :many
SELECT id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status FROM plan_prices
WHERE plan_id = $1
ORDER BY interval
`

func (q *Queries) ListPlanPricesByPlan(ctx context.Context, planID string) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, listPlanPricesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanPrice{}
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Interval,
			&i.Currency,
			&i.UnitAmount,
			&i.Processor,
			&i.ProcessorPriceRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessorEventProcessed = `-- name: MarkProcessorEventProcessed :exec
UPDATE processor_events
SET processed_at = now()
WHERE processor = $1
  AND event_ref = $2
  AND processed_at IS NULL
`

type MarkProcessorEventProcessedParams struct {
	Processor string `json:"processor"`
	EventRef  string `json:"event_ref"`
}

func (q *Queries) MarkProcessorEventProcessed(ctx context.Context, arg MarkProcessorEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markProcessorEventProcessed, arg.Processor, arg.EventRef)
	return err
}

const upsertBillingCustomer = `-- name: UpsertBillingCustomer :one
INSERT INTO billing_customers (
    id, organisation_id, processor, customer_ref, email, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, now(), now()
)
ON CONFLICT (organisation_id) DO UPDATE
SET processor = EXCLUDED.processor,
    customer_ref = EXCLUDED.customer_ref,
    email = EXCLUDED.email,
    updated_at = now()
RETURNING id, organisation_id, processor, customer_ref, email, created_at, updated_at
`

type UpsertBillingCustomerParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Processor      string `json:"processor"`
	CustomerRef    string `json:"customer_ref"`
	Email          string `json:"email"`
}

func (q *Queries) UpsertBillingCustomer(ctx context.Context, arg UpsertBillingCustomerParams) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, upsertBillingCustomer,
		arg.ID,
		arg.OrganisationID,
		arg.Processor,
		arg.CustomerRef,
		arg.Email,
	)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Processor,
		&i.CustomerRef,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlanPrice = `-- name: UpsertPlanPrice :one
INSERT INTO plan_prices (
    id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (plan_id, interval, processor) DO UPDATE
SET currency = EXCLUDED.currency,
    unit_amount = EXCLUDED.unit_amount,
    processor_price_ref = EXCLUDED.processor_price_ref,
    status = EXCLUDED.status
RETURNING id, plan_id, interval, currency, unit_amount, processor, processor_price_ref, status
`

type UpsertPlanPriceParams struct {
	ID                string `json:"id"`
	PlanID            string `json:"plan_id"`
	Interval          string `json:"interval"`
	Currency          string `json:"currency"`
	UnitAmount        int64  `json:"unit_amount"`
	Processor         string `json:"processor"`
	ProcessorPriceRef string `json:"processor_price_ref"`
	Status            string `json:"status"`
}

func (q *Queries) UpsertPlanPrice(ctx context.Context, arg UpsertPlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, upsertPlanPrice,
		arg.ID,
		arg.PlanID,
		arg.Interval,
		arg.Currency,
		arg.UnitAmount,
		arg.Processor,
		arg.ProcessorPriceRef,
		arg.Status,
	)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const upsertSubscriptionFromProcessor = `-- name: UpsertSubscriptionFromProcessor :one
INSERT INTO subscriptions (
    id, organisation_id, plan_id, status, current_period_end, processor, subscription_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (organisation_id) DO UPDATE
SET plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    current_period_end = EXCLUDED.current_period_end,
    processor = EXCLUDED.processor,
    subscription_ref = EXCLUDED.subscription_ref
RETURNING id, organisation_id, plan_id, status, current_period_end, processor, subscription_ref
`

type UpsertSubscriptionFromProcessorParams struct {
	ID               string             `json:"id"`
	OrganisationID   string             `json:"organisation_id"`
	PlanID           string             `json:"plan_id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
	Processor        pgtype.Text        `json:"processor"`
	SubscriptionRef  pgtype.Text        `json:"subscription_ref"`
}

func (q *Queries) UpsertSubscriptionFromProcessor(ctx context.Context, arg UpsertSubscriptionFromProcessorParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscriptionFromProcessor,
		arg.ID,
		arg.OrganisationID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodEnd,
		arg.Processor,
		arg.SubscriptionRef,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.Processor,
		&i.SubscriptionRef,
	)
	return i, err
}
