// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, organisation_id, plan_id, status, current_period_end)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, plan_id, status, current_period_end
`

type CreateSubscriptionParams struct {
	ID               string             `json:"id"`
	OrganisationID   string             `json:"organisation_id"`
	PlanID           string             `json:"plan_id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.OrganisationID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
	)
	return i, err
}

const getPlanByKey = `-- name: GetPlanByKey :one
SELECT id, key, name, status FROM plans
WHERE key = $1
`

func (q *Queries) GetPlanByKey(ctx context.Context, key string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByKey, key)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getSubscriptionByOrganisation = `-- name: GetSubscriptionByOrganisation :one
SELECT id, organisation_id, plan_id, status, current_period_end FROM subscriptions
WHERE organisation_id = $1
`

func (q *Queries) GetSubscriptionByOrganisation(ctx context.Context, organisationID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOrganisation, organisationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
	)
	return i, err
}
