// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_templates.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEmailTemplate = `-- name: ArchiveEmailTemplate :one
UPDATE email_templates
SET status = 'archived', updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address
`

func (q *Queries) ArchiveEmailTemplate(ctx context.Context, id string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, archiveEmailTemplate, id)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodySections,
		&i.FromName,
		&i.FromAddress,
	)
	return i, err
}

const createEmailTemplate = `-- name: CreateEmailTemplate :one
INSERT INTO email_templates (
    id, organisation_id, key, name, description,
    subject, body_text, body_html, body_sections, from_name, from_address, status, is_system
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address
`

type CreateEmailTemplateParams struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	Key            string          `json:"key"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	Subject        string          `json:"subject"`
	BodyText       string          `json:"body_text"`
	BodyHtml       string          `json:"body_html"`
	BodySections   json.RawMessage `json:"body_sections"`
	FromName       string          `json:"from_name"`
	FromAddress    string          `json:"from_address"`
	Status         string          `json:"status"`
	IsSystem       bool            `json:"is_system"`
}

func (q *Queries) CreateEmailTemplate(ctx context.Context, arg CreateEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, createEmailTemplate,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.BodySections,
		arg.FromName,
		arg.FromAddress,
		arg.Status,
		arg.IsSystem,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodySections,
		&i.FromName,
		&i.FromAddress,
	)
	return i, err
}

const getEmailTemplate = `-- name: GetEmailTemplate :one
SELECT id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address FROM email_templates WHERE id = $1
`

func (q *Queries) GetEmailTemplate(ctx context.Context, id string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplate, id)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodySections,
		&i.FromName,
		&i.FromAddress,
	)
	return i, err
}

const getEmailTemplateByOrgKey = `-- name: GetEmailTemplateByOrgKey :one
SELECT id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address FROM email_templates
WHERE organisation_id = $1 AND key = $2
`

type GetEmailTemplateByOrgKeyParams struct {
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
}

func (q *Queries) GetEmailTemplateByOrgKey(ctx context.Context, arg GetEmailTemplateByOrgKeyParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplateByOrgKey, arg.OrganisationID, arg.Key)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodySections,
		&i.FromName,
		&i.FromAddress,
	)
	return i, err
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address FROM email_templates
WHERE organisation_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY is_system DESC, key ASC
`

type ListEmailTemplatesParams struct {
	OrganisationID string      `json:"organisation_id"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) ListEmailTemplates(ctx context.Context, arg ListEmailTemplatesParams) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates, arg.OrganisationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailTemplate{}
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtml,
			&i.Status,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodySections,
			&i.FromName,
			&i.FromAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailTemplate = `-- name: UpdateEmailTemplate :one
UPDATE email_templates SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    subject = COALESCE($4, subject),
    body_text = COALESCE($5, body_text),
    body_html = COALESCE($6, body_html),
    body_sections = COALESCE($7, body_sections),
    from_name = COALESCE($8, from_name),
    from_address = COALESCE($9, from_address),
    status = COALESCE($10, status),
    updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, key, name, description, subject, body_text, body_html, status, is_system, created_at, updated_at, body_sections, from_name, from_address
`

type UpdateEmailTemplateParams struct {
	ID           string      `json:"id"`
	Name         pgtype.Text `json:"name"`
	Description  pgtype.Text `json:"description"`
	Subject      pgtype.Text `json:"subject"`
	BodyText     pgtype.Text `json:"body_text"`
	BodyHtml     pgtype.Text `json:"body_html"`
	BodySections []byte      `json:"body_sections"`
	FromName     pgtype.Text `json:"from_name"`
	FromAddress  pgtype.Text `json:"from_address"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, updateEmailTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.BodySections,
		arg.FromName,
		arg.FromAddress,
		arg.Status,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodySections,
		&i.FromName,
		&i.FromAddress,
	)
	return i, err
}
