// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_flags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeatureFlag = `-- name: CreateFeatureFlag :one
INSERT INTO feature_flags (id, organisation_id, key, description, enabled, rollout_percentage)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, key, description, enabled, rollout_percentage, created_at, updated_at
`

type CreateFeatureFlagParams struct {
	ID                string `json:"id"`
	OrganisationID    string `json:"organisation_id"`
	Key               string `json:"key"`
	Description       string `json:"description"`
	Enabled           bool   `json:"enabled"`
	RolloutPercentage int32  `json:"rollout_percentage"`
}

func (q *Queries) CreateFeatureFlag(ctx context.Context, arg CreateFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, createFeatureFlag,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Description,
		arg.Enabled,
		arg.RolloutPercentage,
	)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeatureFlag = `-- name: DeleteFeatureFlag :exec
DELETE FROM feature_flags
WHERE id = $1
  AND organisation_id = $2
`

type DeleteFeatureFlagParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteFeatureFlag(ctx context.Context, arg DeleteFeatureFlagParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureFlag, arg.ID, arg.OrganisationID)
	return err
}

const deleteFeatureFlagOverrides = `-- name: DeleteFeatureFlagOverrides :exec
DELETE FROM feature_flag_overrides
WHERE feature_flag_id = $1
`

func (q *Queries) DeleteFeatureFlagOverrides(ctx context.Context, featureFlagID string) error {
	_, err := q.db.Exec(ctx, deleteFeatureFlagOverrides, featureFlagID)
	return err
}

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT id, organisation_id, key, description, enabled, rollout_percentage, created_at, updated_at FROM feature_flags
WHERE id = $1
`

func (q *Queries) GetFeatureFlag(ctx context.Context, id string) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlag, id)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlagByOrgKey = `-- name: GetFeatureFlagByOrgKey :one
SELECT id, organisation_id, key, description, enabled, rollout_percentage, created_at, updated_at FROM feature_flags
WHERE organisation_id = $1
  AND key = $2
`

type GetFeatureFlagByOrgKeyParams struct {
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
}

func (q *Queries) GetFeatureFlagByOrgKey(ctx context.Context, arg GetFeatureFlagByOrgKeyParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagByOrgKey, arg.OrganisationID, arg.Key)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlagOverride = `-- name: GetFeatureFlagOverride :one
SELECT feature_flag_id, subject_id, effect, created_at FROM feature_flag_overrides
WHERE feature_flag_id = $1
  AND subject_id = $2
`

type GetFeatureFlagOverrideParams struct {
	FeatureFlagID string `json:"feature_flag_id"`
	SubjectID     string `json:"subject_id"`
}

func (q *Queries) GetFeatureFlagOverride(ctx context.Context, arg GetFeatureFlagOverrideParams) (FeatureFlagOverride, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagOverride, arg.FeatureFlagID, arg.SubjectID)
	var i FeatureFlagOverride
	err := row.Scan(
		&i.FeatureFlagID,
		&i.SubjectID,
		&i.Effect,
		&i.CreatedAt,
	)
	return i, err
}

const listFeatureFlagOverrides = `-- name: ListFeatureFlagOverrides :many
SELECT feature_flag_id, subject_id, effect, created_at FROM feature_flag_overrides
WHERE feature_flag_id = $1
ORDER BY subject_id
`

func (q *Queries) ListFeatureFlagOverrides(ctx context.Context, featureFlagID string) ([]FeatureFlagOverride, error) {
	rows, err := q.db.Query(ctx, listFeatureFlagOverrides, featureFlagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlagOverride{}
	for rows.Next() {
		var i FeatureFlagOverride
		if err := rows.Scan(
			&i.FeatureFlagID,
			&i.SubjectID,
			&i.Effect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlagsByOrg = `-- name: ListFeatureFlagsByOrg :many
SELECT id, organisation_id, key, description, enabled, rollout_percentage, created_at, updated_at FROM feature_flags
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListFeatureFlagsByOrg(ctx context.Context, organisationID string) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlagsByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Description,
			&i.Enabled,
			&i.RolloutPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureFlag = `-- name: UpdateFeatureFlag :one
UPDATE feature_flags
SET description = COALESCE($3, description),
    enabled = COALESCE($4, enabled),
    rollout_percentage = COALESCE($5, rollout_percentage),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
RETURNING id, organisation_id, key, description, enabled, rollout_percentage, created_at, updated_at
`

type UpdateFeatureFlagParams struct {
	ID                string      `json:"id"`
	OrganisationID    string      `json:"organisation_id"`
	Description       pgtype.Text `json:"description"`
	Enabled           pgtype.Bool `json:"enabled"`
	RolloutPercentage pgtype.Int4 `json:"rollout_percentage"`
}

func (q *Queries) UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, updateFeatureFlag,
		arg.ID,
		arg.OrganisationID,
		arg.Description,
		arg.Enabled,
		arg.RolloutPercentage,
	)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeatureFlagOverride = `-- name: UpsertFeatureFlagOverride :exec
INSERT INTO feature_flag_overrides (feature_flag_id, subject_id, effect)
VALUES ($1, $2, $3)
ON CONFLICT (feature_flag_id, subject_id) DO UPDATE
SET effect = EXCLUDED.effect
`

type UpsertFeatureFlagOverrideParams struct {
	FeatureFlagID string `json:"feature_flag_id"`
	SubjectID     string `json:"subject_id"`
	Effect        string `json:"effect"`
}

func (q *Queries) UpsertFeatureFlagOverride(ctx context.Context, arg UpsertFeatureFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertFeatureFlagOverride, arg.FeatureFlagID, arg.SubjectID, arg.Effect)
	return err
}
