// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hardening.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, name, key_prefix, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, name, key_prefix, key_hash, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	KeyHash   string `json:"key_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_prefix, key_hash, created_at, revoked_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (id, actor, method, path, status_code, organisation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor, method, path, status_code, organisation_id, created_at
`

type InsertAuditEventParams struct {
	ID             string      `json:"id"`
	Actor          string      `json:"actor"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	StatusCode     int32       `json:"status_code"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.OrganisationID,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.OrganisationID,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, key_hash, created_at, revoked_at FROM api_keys
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor, method, path, status_code, organisation_id, created_at FROM audit_events
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.OrganisationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, name, key_prefix, key_hash, created_at, revoked_at
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
