// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response_status, response_body, created_at FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_hash, response_status, response_body)
VALUES ($1, $2, $3, $4)
RETURNING key, request_hash, response_status, response_body, created_at
`

type InsertIdempotencyKeyParams struct {
	Key            string `json:"key"`
	RequestHash    string `json:"request_hash"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.Key,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
