// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package sqlc

import (
	"context"
)

const deleteOrganisationIntegration = `-- name: DeleteOrganisationIntegration :exec
DELETE FROM organisation_integrations
WHERE organisation_id = $1 AND provider = $2
`

type DeleteOrganisationIntegrationParams struct {
	OrganisationID string `json:"organisation_id"`
	Provider       string `json:"provider"`
}

func (q *Queries) DeleteOrganisationIntegration(ctx context.Context, arg DeleteOrganisationIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteOrganisationIntegration, arg.OrganisationID, arg.Provider)
	return err
}

const getOrganisationIntegration = `-- name: GetOrganisationIntegration :one
SELECT organisation_id, provider, status, secret_key, public_key, updated_at FROM organisation_integrations
WHERE organisation_id = $1 AND provider = $2
`

type GetOrganisationIntegrationParams struct {
	OrganisationID string `json:"organisation_id"`
	Provider       string `json:"provider"`
}

func (q *Queries) GetOrganisationIntegration(ctx context.Context, arg GetOrganisationIntegrationParams) (OrganisationIntegration, error) {
	row := q.db.QueryRow(ctx, getOrganisationIntegration, arg.OrganisationID, arg.Provider)
	var i OrganisationIntegration
	err := row.Scan(
		&i.OrganisationID,
		&i.Provider,
		&i.Status,
		&i.SecretKey,
		&i.PublicKey,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisationIntegrations = `-- name: ListOrganisationIntegrations :many
SELECT organisation_id, provider, status, secret_key, public_key, updated_at FROM organisation_integrations
WHERE organisation_id = $1
ORDER BY provider
`

func (q *Queries) ListOrganisationIntegrations(ctx context.Context, organisationID string) ([]OrganisationIntegration, error) {
	rows, err := q.db.Query(ctx, listOrganisationIntegrations, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationIntegration{}
	for rows.Next() {
		var i OrganisationIntegration
		if err := rows.Scan(
			&i.OrganisationID,
			&i.Provider,
			&i.Status,
			&i.SecretKey,
			&i.PublicKey,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrganisationIntegration = `-- name: UpsertOrganisationIntegration :one
INSERT INTO organisation_integrations (
    organisation_id, provider, status, secret_key, public_key, updated_at
)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (organisation_id, provider) DO UPDATE
SET status = EXCLUDED.status,
    secret_key = CASE
        WHEN EXCLUDED.secret_key = '' THEN organisation_integrations.secret_key
        ELSE EXCLUDED.secret_key
    END,
    public_key = CASE
        WHEN EXCLUDED.public_key = '' THEN organisation_integrations.public_key
        ELSE EXCLUDED.public_key
    END,
    updated_at = now()
RETURNING organisation_id, provider, status, secret_key, public_key, updated_at
`

type UpsertOrganisationIntegrationParams struct {
	OrganisationID string `json:"organisation_id"`
	Provider       string `json:"provider"`
	Status         string `json:"status"`
	SecretKey      string `json:"secret_key"`
	PublicKey      string `json:"public_key"`
}

func (q *Queries) UpsertOrganisationIntegration(ctx context.Context, arg UpsertOrganisationIntegrationParams) (OrganisationIntegration, error) {
	row := q.db.QueryRow(ctx, upsertOrganisationIntegration,
		arg.OrganisationID,
		arg.Provider,
		arg.Status,
		arg.SecretKey,
		arg.PublicKey,
	)
	var i OrganisationIntegration
	err := row.Scan(
		&i.OrganisationID,
		&i.Provider,
		&i.Status,
		&i.SecretKey,
		&i.PublicKey,
		&i.UpdatedAt,
	)
	return i, err
}
