// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMembership = `-- name: AcceptMembership :one
UPDATE memberships
SET status = 'active'
WHERE id = $1 AND status = 'invited'
RETURNING id, organisation_id, user_id, role_id, status, created_at
`

func (q *Queries) AcceptMembership(ctx context.Context, id string) (Membership, error) {
	row := q.db.QueryRow(ctx, acceptMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, organisation_id, user_id, role_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, user_id, role_id, status, created_at
`

type CreateMembershipParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	UserID         string `json:"user_id"`
	RoleID         string `json:"role_id"`
	Status         string `json:"status"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.OrganisationID,
		arg.UserID,
		arg.RoleID,
		arg.Status,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMembershipByOrgAndUser = `-- name: GetActiveMembershipByOrgAndUser :one
SELECT id, organisation_id, user_id, role_id, status, created_at FROM memberships
WHERE organisation_id = $1
  AND user_id = $2
  AND status = 'active'
`

type GetActiveMembershipByOrgAndUserParams struct {
	OrganisationID string `json:"organisation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetActiveMembershipByOrgAndUser(ctx context.Context, arg GetActiveMembershipByOrgAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByOrgAndUser, arg.OrganisationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organisation_id, user_id, role_id, status, created_at FROM memberships
WHERE id = $1
`

func (q *Queries) GetMembership(ctx context.Context, id string) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByOrgAndUser = `-- name: GetMembershipByOrgAndUser :one
SELECT id, organisation_id, user_id, role_id, status, created_at FROM memberships
WHERE organisation_id = $1 AND user_id = $2
`

type GetMembershipByOrgAndUserParams struct {
	OrganisationID string `json:"organisation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMembershipByOrgAndUser(ctx context.Context, arg GetMembershipByOrgAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByOrgAndUser, arg.OrganisationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipDetail = `-- name: GetMembershipDetail :one
SELECT
  m.id, m.organisation_id, m.user_id, m.role_id, m.status, m.created_at,
  u.email AS user_email,
  u.name AS user_name,
  r.key AS role_key
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN roles r ON r.id = m.role_id
WHERE m.id = $1
`

type GetMembershipDetailRow struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	UserID         string    `json:"user_id"`
	RoleID         string    `json:"role_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UserEmail      string    `json:"user_email"`
	UserName       string    `json:"user_name"`
	RoleKey        string    `json:"role_key"`
}

func (q *Queries) GetMembershipDetail(ctx context.Context, id string) (GetMembershipDetailRow, error) {
	row := q.db.QueryRow(ctx, getMembershipDetail, id)
	var i GetMembershipDetailRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UserEmail,
		&i.UserName,
		&i.RoleKey,
	)
	return i, err
}

const listMembershipsByOrganisation = `-- name: ListMembershipsByOrganisation :many
SELECT
  m.id, m.organisation_id, m.user_id, m.role_id, m.status, m.created_at,
  u.email AS user_email,
  u.name AS user_name,
  r.key AS role_key
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN roles r ON r.id = m.role_id
WHERE m.organisation_id = $1
ORDER BY m.created_at, m.id
`

type ListMembershipsByOrganisationRow struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	UserID         string    `json:"user_id"`
	RoleID         string    `json:"role_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UserEmail      string    `json:"user_email"`
	UserName       string    `json:"user_name"`
	RoleKey        string    `json:"role_key"`
}

func (q *Queries) ListMembershipsByOrganisation(ctx context.Context, organisationID string) ([]ListMembershipsByOrganisationRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByOrganisationRow{}
	for rows.Next() {
		var i ListMembershipsByOrganisationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.RoleKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
  m.id, m.organisation_id, m.user_id, m.role_id, m.status, m.created_at,
  o.name AS organisation_name,
  o.slug AS organisation_slug,
  o.status AS organisation_status,
  r.key AS role_key
FROM memberships m
JOIN organisations o ON o.id = m.organisation_id
JOIN roles r ON r.id = m.role_id
WHERE m.user_id = $1
ORDER BY m.created_at, m.id
`

type ListMembershipsByUserRow struct {
	ID                 string    `json:"id"`
	OrganisationID     string    `json:"organisation_id"`
	UserID             string    `json:"user_id"`
	RoleID             string    `json:"role_id"`
	Status             string    `json:"status"`
	CreatedAt          time.Time `json:"created_at"`
	OrganisationName   string    `json:"organisation_name"`
	OrganisationSlug   string    `json:"organisation_slug"`
	OrganisationStatus string    `json:"organisation_status"`
	RoleKey            string    `json:"role_key"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.RoleID,
			&i.Status,
			&i.CreatedAt,
			&i.OrganisationName,
			&i.OrganisationSlug,
			&i.OrganisationStatus,
			&i.RoleKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMembership = `-- name: RevokeMembership :one
UPDATE memberships
SET status = 'revoked'
WHERE id = $1
RETURNING id, organisation_id, user_id, role_id, status, created_at
`

func (q *Queries) RevokeMembership(ctx context.Context, id string) (Membership, error) {
	row := q.db.QueryRow(ctx, revokeMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE memberships
SET
  role_id = COALESCE($1, role_id),
  status = COALESCE($2, status)
WHERE id = $3
RETURNING id, organisation_id, user_id, role_id, status, created_at
`

type UpdateMembershipParams struct {
	RoleID pgtype.Text `json:"role_id"`
	Status pgtype.Text `json:"status"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.RoleID, arg.Status, arg.ID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
