// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AppUser struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	ExternalID     pgtype.Text     `json:"external_id"`
	Email          pgtype.Text     `json:"email"`
	DisplayName    string          `json:"display_name"`
	Status         string          `json:"status"`
	Attributes     json.RawMessage `json:"attributes"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AttributeDefinition struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	Key            string          `json:"key"`
	Label          string          `json:"label"`
	Description    string          `json:"description"`
	ValueType      string          `json:"value_type"`
	Section        string          `json:"section"`
	SortOrder      int32           `json:"sort_order"`
	Required       bool            `json:"required"`
	EnumValues     json.RawMessage `json:"enum_values"`
	IsPii          bool            `json:"is_pii"`
	Status         string          `json:"status"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	IsSystem       bool            `json:"is_system"`
}

type AuditEvent struct {
	ID             string      `json:"id"`
	Actor          string      `json:"actor"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	StatusCode     int32       `json:"status_code"`
	OrganisationID pgtype.Text `json:"organisation_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Automation struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	Name           string          `json:"name"`
	Trigger        string          `json:"trigger"`
	Enabled        bool            `json:"enabled"`
	Conditions     json.RawMessage `json:"conditions"`
	Actions        json.RawMessage `json:"actions"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AutomationRun struct {
	ID             string          `json:"id"`
	OrganisationID string          `json:"organisation_id"`
	AutomationID   string          `json:"automation_id"`
	Trigger        string          `json:"trigger"`
	Status         string          `json:"status"`
	Detail         string          `json:"detail"`
	Payload        json.RawMessage `json:"payload"`
	CreatedAt      time.Time       `json:"created_at"`
}

type BillingCustomer struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	Processor      string    `json:"processor"`
	CustomerRef    string    `json:"customer_ref"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type EmailTemplate struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	Key            string    `json:"key"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	Subject        string    `json:"subject"`
	BodyText       string    `json:"body_text"`
	BodyHtml       string    `json:"body_html"`
	Status         string    `json:"status"`
	IsSystem       bool      `json:"is_system"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Entitlement struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Description string `json:"description"`
}

type IdempotencyKey struct {
	Key            string          `json:"key"`
	RequestHash    string          `json:"request_hash"`
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Membership struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	UserID         string    `json:"user_id"`
	RoleID         string    `json:"role_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}

type Organisation struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	LogoUrl      string    `json:"logo_url"`
	PrimaryColor string    `json:"primary_color"`
	AccentColor  string    `json:"accent_color"`
	EmailFooter  string    `json:"email_footer"`
	EmailFont    string    `json:"email_font"`
}

type OrganisationEntitlement struct {
	OrganisationID string `json:"organisation_id"`
	EntitlementID  string `json:"entitlement_id"`
	Effect         string `json:"effect"`
}

type Permission struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Category    string `json:"category"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
}

type Plan struct {
	ID     string `json:"id"`
	Key    string `json:"key"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type PlanEntitlement struct {
	PlanID        string `json:"plan_id"`
	EntitlementID string `json:"entitlement_id"`
}

type PlanPrice struct {
	ID                string `json:"id"`
	PlanID            string `json:"plan_id"`
	Interval          string `json:"interval"`
	Currency          string `json:"currency"`
	UnitAmount        int64  `json:"unit_amount"`
	Processor         string `json:"processor"`
	ProcessorPriceRef string `json:"processor_price_ref"`
	Status            string `json:"status"`
}

type ProcessorEvent struct {
	ID          string             `json:"id"`
	Processor   string             `json:"processor"`
	EventRef    string             `json:"event_ref"`
	EventType   string             `json:"event_type"`
	Payload     json.RawMessage    `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Role struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	IsSystem       bool   `json:"is_system"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Subscription struct {
	ID               string             `json:"id"`
	OrganisationID   string             `json:"organisation_id"`
	PlanID           string             `json:"plan_id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
	Processor        pgtype.Text        `json:"processor"`
	SubscriptionRef  pgtype.Text        `json:"subscription_ref"`
}

type User struct {
	ID            string      `json:"id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	PlatformAdmin bool        `json:"platform_admin"`
	GoogleSub     pgtype.Text `json:"google_sub"`
	AvatarUrl     string      `json:"avatar_url"`
}
