// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AuditEvent struct {
	ID             string      `json:"id"`
	Actor          string      `json:"actor"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	StatusCode     int32       `json:"status_code"`
	OrganisationID pgtype.Text `json:"organisation_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Entitlement struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Description string `json:"description"`
}

type IdempotencyKey struct {
	Key            string    `json:"key"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
}

type Membership struct {
	ID             string    `json:"id"`
	OrganisationID string    `json:"organisation_id"`
	UserID         string    `json:"user_id"`
	RoleID         string    `json:"role_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}

type Organisation struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OrganisationEntitlement struct {
	OrganisationID string `json:"organisation_id"`
	EntitlementID  string `json:"entitlement_id"`
	Effect         string `json:"effect"`
}

type Permission struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Category    string `json:"category"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
}

type Plan struct {
	ID     string `json:"id"`
	Key    string `json:"key"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type PlanEntitlement struct {
	PlanID        string `json:"plan_id"`
	EntitlementID string `json:"entitlement_id"`
}

type Role struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	IsSystem       bool   `json:"is_system"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Subscription struct {
	ID               string             `json:"id"`
	OrganisationID   string             `json:"organisation_id"`
	PlanID           string             `json:"plan_id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

type User struct {
	ID            string      `json:"id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	PlatformAdmin bool        `json:"platform_admin"`
	GoogleSub     pgtype.Text `json:"google_sub"`
}
