// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPIKeysByOrg = `-- name: CountActiveAPIKeysByOrg :one
SELECT COUNT(*)::bigint
FROM api_keys
WHERE organisation_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeysByOrg(ctx context.Context, organisationID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeysByOrg, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAppUsersByOrg = `-- name: CountAppUsersByOrg :one
SELECT COUNT(*)::bigint
FROM app_users
WHERE organisation_id = $1
`

func (q *Queries) CountAppUsersByOrg(ctx context.Context, organisationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppUsersByOrg, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAutomationsByOrg = `-- name: CountAutomationsByOrg :one
SELECT COUNT(*)::bigint
FROM automations
WHERE organisation_id = $1
`

func (q *Queries) CountAutomationsByOrg(ctx context.Context, organisationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAutomationsByOrg, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProductFeaturesByOrg = `-- name: CountProductFeaturesByOrg :one
SELECT COUNT(*)::bigint
FROM entitlements
WHERE organisation_id = $1 AND scope = 'product'
`

func (q *Queries) CountProductFeaturesByOrg(ctx context.Context, organisationID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProductFeaturesByOrg, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProductPlansByOrg = `-- name: CountProductPlansByOrg :one
SELECT COUNT(*)::bigint
FROM product_plans
WHERE organisation_id = $1
`

func (q *Queries) CountProductPlansByOrg(ctx context.Context, organisationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductPlansByOrg, organisationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrganisationOnboarding = `-- name: GetOrganisationOnboarding :one
SELECT organisation_id, dismissed_at, updated_at
FROM organisation_onboarding
WHERE organisation_id = $1
`

func (q *Queries) GetOrganisationOnboarding(ctx context.Context, organisationID string) (OrganisationOnboarding, error) {
	row := q.db.QueryRow(ctx, getOrganisationOnboarding, organisationID)
	var i OrganisationOnboarding
	err := row.Scan(&i.OrganisationID, &i.DismissedAt, &i.UpdatedAt)
	return i, err
}

const upsertOrganisationOnboardingDismissed = `-- name: UpsertOrganisationOnboardingDismissed :one
INSERT INTO organisation_onboarding (organisation_id, dismissed_at, updated_at)
VALUES ($1, now(), now())
ON CONFLICT (organisation_id) DO UPDATE
SET dismissed_at = now(),
    updated_at = now()
RETURNING organisation_id, dismissed_at, updated_at
`

func (q *Queries) UpsertOrganisationOnboardingDismissed(ctx context.Context, organisationID string) (OrganisationOnboarding, error) {
	row := q.db.QueryRow(ctx, upsertOrganisationOnboardingDismissed, organisationID)
	var i OrganisationOnboarding
	err := row.Scan(&i.OrganisationID, &i.DismissedAt, &i.UpdatedAt)
	return i, err
}
