// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOrganisation = `-- name: ArchiveOrganisation :one
UPDATE organisations
SET status = 'archived', updated_at = now()
WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at
`

func (q *Queries) ArchiveOrganisation(ctx context.Context, id string) (Organisation, error) {
	row := q.db.QueryRow(ctx, archiveOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (id, name, slug, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, status, created_at, updated_at
`

type CreateOrganisationParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Status string `json:"status"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganisation = `-- name: GetOrganisation :one
SELECT id, name, slug, status, created_at, updated_at FROM organisations
WHERE id = $1
`

func (q *Queries) GetOrganisation(ctx context.Context, id string) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisations = `-- name: ListOrganisations :many
SELECT id, name, slug, status, created_at, updated_at FROM organisations
WHERE ($1::text IS NULL OR status = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2 || '%'
    OR slug ILIKE '%' || $2 || '%'
  )
  AND ($3::text IS NULL OR id > $3)
ORDER BY id
LIMIT $4
`

type ListOrganisationsParams struct {
	Status pgtype.Text `json:"status"`
	Q      pgtype.Text `json:"q"`
	Cursor pgtype.Text `json:"cursor"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListOrganisations(ctx context.Context, arg ListOrganisationsParams) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, listOrganisations,
		arg.Status,
		arg.Q,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organisation{}
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganisationsForUser = `-- name: ListOrganisationsForUser :many
SELECT o.id, o.name, o.slug, o.status, o.created_at, o.updated_at
FROM organisations o
JOIN memberships m ON m.organisation_id = o.id
WHERE m.user_id = $1
  AND m.status IN ('active', 'invited')
  AND ($2::text IS NULL OR o.status = $2)
  AND (
    $3::text IS NULL
    OR o.name ILIKE '%' || $3 || '%'
    OR o.slug ILIKE '%' || $3 || '%'
  )
  AND ($4::text IS NULL OR o.id > $4)
ORDER BY o.id
LIMIT $5
`

type ListOrganisationsForUserParams struct {
	UserID string      `json:"user_id"`
	Status pgtype.Text `json:"status"`
	Q      pgtype.Text `json:"q"`
	Cursor pgtype.Text `json:"cursor"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListOrganisationsForUser(ctx context.Context, arg ListOrganisationsForUserParams) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, listOrganisationsForUser,
		arg.UserID,
		arg.Status,
		arg.Q,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organisation{}
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE organisations
SET
  name = COALESCE($1, name),
  status = COALESCE($2, status),
  updated_at = now()
WHERE id = $3
RETURNING id, name, slug, status, created_at, updated_at
`

type UpdateOrganisationParams struct {
	Name   pgtype.Text `json:"name"`
	Status pgtype.Text `json:"status"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, updateOrganisation, arg.Name, arg.Status, arg.ID)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
