// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation_databases.sql

package sqlc

import (
	"context"
)

const createOrganisationDatabase = `-- name: CreateOrganisationDatabase :one
INSERT INTO organisation_databases (
    id, organisation_id, name, driver, host, port, database_name,
    username, password, ssl_mode, status, last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error
`

type CreateOrganisationDatabaseParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Name           string `json:"name"`
	Driver         string `json:"driver"`
	Host           string `json:"host"`
	Port           int32  `json:"port"`
	DatabaseName   string `json:"database_name"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	SslMode        string `json:"ssl_mode"`
	Status         string `json:"status"`
	LastError      string `json:"last_error"`
}

func (q *Queries) CreateOrganisationDatabase(ctx context.Context, arg CreateOrganisationDatabaseParams) (OrganisationDatabase, error) {
	row := q.db.QueryRow(ctx, createOrganisationDatabase,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Driver,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.Password,
		arg.SslMode,
		arg.Status,
		arg.LastError,
	)
	var i OrganisationDatabase
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.SslMode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckedAt,
		&i.LastError,
	)
	return i, err
}

const deleteOrganisationDatabase = `-- name: DeleteOrganisationDatabase :exec
DELETE FROM organisation_databases
WHERE id = $1 AND organisation_id = $2
`

type DeleteOrganisationDatabaseParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteOrganisationDatabase(ctx context.Context, arg DeleteOrganisationDatabaseParams) error {
	_, err := q.db.Exec(ctx, deleteOrganisationDatabase, arg.ID, arg.OrganisationID)
	return err
}

const getOrganisationDatabase = `-- name: GetOrganisationDatabase :one
SELECT id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error FROM organisation_databases
WHERE id = $1
`

func (q *Queries) GetOrganisationDatabase(ctx context.Context, id string) (OrganisationDatabase, error) {
	row := q.db.QueryRow(ctx, getOrganisationDatabase, id)
	var i OrganisationDatabase
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.SslMode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckedAt,
		&i.LastError,
	)
	return i, err
}

const getOrganisationDatabaseForOrg = `-- name: GetOrganisationDatabaseForOrg :one
SELECT id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error FROM organisation_databases
WHERE id = $1 AND organisation_id = $2
`

type GetOrganisationDatabaseForOrgParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) GetOrganisationDatabaseForOrg(ctx context.Context, arg GetOrganisationDatabaseForOrgParams) (OrganisationDatabase, error) {
	row := q.db.QueryRow(ctx, getOrganisationDatabaseForOrg, arg.ID, arg.OrganisationID)
	var i OrganisationDatabase
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.SslMode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckedAt,
		&i.LastError,
	)
	return i, err
}

const listOrganisationDatabases = `-- name: ListOrganisationDatabases :many
SELECT id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error FROM organisation_databases
WHERE organisation_id = $1
ORDER BY name, created_at
`

func (q *Queries) ListOrganisationDatabases(ctx context.Context, organisationID string) ([]OrganisationDatabase, error) {
	rows, err := q.db.Query(ctx, listOrganisationDatabases, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationDatabase{}
	for rows.Next() {
		var i OrganisationDatabase
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Driver,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.Password,
			&i.SslMode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCheckedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisationDatabase = `-- name: UpdateOrganisationDatabase :one
UPDATE organisation_databases
SET name = $1,
    host = $2,
    port = $3,
    database_name = $4,
    username = $5,
    password = CASE
        WHEN $6::text = '' THEN password
        ELSE $6::text
    END,
    ssl_mode = $7,
    updated_at = now()
WHERE id = $8 AND organisation_id = $9
RETURNING id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error
`

type UpdateOrganisationDatabaseParams struct {
	Name           string `json:"name"`
	Host           string `json:"host"`
	Port           int32  `json:"port"`
	DatabaseName   string `json:"database_name"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	SslMode        string `json:"ssl_mode"`
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) UpdateOrganisationDatabase(ctx context.Context, arg UpdateOrganisationDatabaseParams) (OrganisationDatabase, error) {
	row := q.db.QueryRow(ctx, updateOrganisationDatabase,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.Password,
		arg.SslMode,
		arg.ID,
		arg.OrganisationID,
	)
	var i OrganisationDatabase
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.SslMode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckedAt,
		&i.LastError,
	)
	return i, err
}

const updateOrganisationDatabaseCheck = `-- name: UpdateOrganisationDatabaseCheck :one
UPDATE organisation_databases
SET status = $1,
    last_checked_at = now(),
    last_error = $2,
    updated_at = now()
WHERE id = $3 AND organisation_id = $4
RETURNING id, organisation_id, name, driver, host, port, database_name, username, password, ssl_mode, status, created_at, updated_at, last_checked_at, last_error
`

type UpdateOrganisationDatabaseCheckParams struct {
	Status         string `json:"status"`
	LastError      string `json:"last_error"`
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) UpdateOrganisationDatabaseCheck(ctx context.Context, arg UpdateOrganisationDatabaseCheckParams) (OrganisationDatabase, error) {
	row := q.db.QueryRow(ctx, updateOrganisationDatabaseCheck,
		arg.Status,
		arg.LastError,
		arg.ID,
		arg.OrganisationID,
	)
	var i OrganisationDatabase
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.SslMode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckedAt,
		&i.LastError,
	)
	return i, err
}
