// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOrganisation = `-- name: ArchiveOrganisation :one
UPDATE organisations
SET status = 'archived', updated_at = now()
WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode
`

func (q *Queries) ArchiveOrganisation(ctx context.Context, id string) (Organisation, error) {
	row := q.db.QueryRow(ctx, archiveOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.EmailFooter,
		&i.EmailFont,
		&i.AppUserAuthority,
		&i.AppUserIngestUpsertKey,
		&i.AppUserAttributesMode,
	)
	return i, err
}

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (id, name, slug, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode
`

type CreateOrganisationParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Status string `json:"status"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.EmailFooter,
		&i.EmailFont,
		&i.AppUserAuthority,
		&i.AppUserIngestUpsertKey,
		&i.AppUserAttributesMode,
	)
	return i, err
}

const deleteOrganisation = `-- name: DeleteOrganisation :exec
DELETE FROM organisations
WHERE id = $1
`

func (q *Queries) DeleteOrganisation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganisation, id)
	return err
}

const getOrganisation = `-- name: GetOrganisation :one
SELECT id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode FROM organisations
WHERE id = $1
`

func (q *Queries) GetOrganisation(ctx context.Context, id string) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.EmailFooter,
		&i.EmailFont,
		&i.AppUserAuthority,
		&i.AppUserIngestUpsertKey,
		&i.AppUserAttributesMode,
	)
	return i, err
}

const listOrganisations = `-- name: ListOrganisations :many
SELECT id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode FROM organisations
WHERE ($1::text IS NULL OR status = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2 || '%'
    OR slug ILIKE '%' || $2 || '%'
  )
  AND ($3::text IS NULL OR id > $3)
ORDER BY id
LIMIT $4
`

type ListOrganisationsParams struct {
	Status pgtype.Text `json:"status"`
	Q      pgtype.Text `json:"q"`
	Cursor pgtype.Text `json:"cursor"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListOrganisations(ctx context.Context, arg ListOrganisationsParams) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, listOrganisations,
		arg.Status,
		arg.Q,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organisation{}
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.EmailFooter,
			&i.EmailFont,
			&i.AppUserAuthority,
			&i.AppUserIngestUpsertKey,
			&i.AppUserAttributesMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganisationsForUser = `-- name: ListOrganisationsForUser :many
SELECT o.id, o.name, o.slug, o.status, o.created_at, o.updated_at, o.logo_url, o.primary_color, o.accent_color, o.email_footer, o.email_font, o.app_user_authority, o.app_user_ingest_upsert_key, o.app_user_attributes_mode
FROM organisations o
JOIN memberships m ON m.organisation_id = o.id
WHERE m.user_id = $1
  AND m.status IN ('active', 'invited')
  AND ($2::text IS NULL OR o.status = $2)
  AND (
    $3::text IS NULL
    OR o.name ILIKE '%' || $3 || '%'
    OR o.slug ILIKE '%' || $3 || '%'
  )
  AND ($4::text IS NULL OR o.id > $4)
ORDER BY o.id
LIMIT $5
`

type ListOrganisationsForUserParams struct {
	UserID string      `json:"user_id"`
	Status pgtype.Text `json:"status"`
	Q      pgtype.Text `json:"q"`
	Cursor pgtype.Text `json:"cursor"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListOrganisationsForUser(ctx context.Context, arg ListOrganisationsForUserParams) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, listOrganisationsForUser,
		arg.UserID,
		arg.Status,
		arg.Q,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organisation{}
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.EmailFooter,
			&i.EmailFont,
			&i.AppUserAuthority,
			&i.AppUserIngestUpsertKey,
			&i.AppUserAttributesMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganisationLogoURL = `-- name: SetOrganisationLogoURL :one
UPDATE organisations
SET logo_url = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode
`

type SetOrganisationLogoURLParams struct {
	ID      string `json:"id"`
	LogoUrl string `json:"logo_url"`
}

func (q *Queries) SetOrganisationLogoURL(ctx context.Context, arg SetOrganisationLogoURLParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, setOrganisationLogoURL, arg.ID, arg.LogoUrl)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.EmailFooter,
		&i.EmailFont,
		&i.AppUserAuthority,
		&i.AppUserIngestUpsertKey,
		&i.AppUserAttributesMode,
	)
	return i, err
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE organisations
SET
  name = COALESCE($1, name),
  status = COALESCE($2, status),
  primary_color = COALESCE($3, primary_color),
  accent_color = COALESCE($4, accent_color),
  email_footer = COALESCE($5, email_footer),
  email_font = COALESCE($6, email_font),
  app_user_authority = COALESCE($7, app_user_authority),
  app_user_ingest_upsert_key = COALESCE($8, app_user_ingest_upsert_key),
  app_user_attributes_mode = COALESCE($9, app_user_attributes_mode),
  updated_at = now()
WHERE id = $10
RETURNING id, name, slug, status, created_at, updated_at, logo_url, primary_color, accent_color, email_footer, email_font, app_user_authority, app_user_ingest_upsert_key, app_user_attributes_mode
`

type UpdateOrganisationParams struct {
	Name                   pgtype.Text `json:"name"`
	Status                 pgtype.Text `json:"status"`
	PrimaryColor           pgtype.Text `json:"primary_color"`
	AccentColor            pgtype.Text `json:"accent_color"`
	EmailFooter            pgtype.Text `json:"email_footer"`
	EmailFont              pgtype.Text `json:"email_font"`
	AppUserAuthority       pgtype.Text `json:"app_user_authority"`
	AppUserIngestUpsertKey pgtype.Text `json:"app_user_ingest_upsert_key"`
	AppUserAttributesMode  pgtype.Text `json:"app_user_attributes_mode"`
	ID                     string      `json:"id"`
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, updateOrganisation,
		arg.Name,
		arg.Status,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.EmailFooter,
		arg.EmailFont,
		arg.AppUserAuthority,
		arg.AppUserIngestUpsertKey,
		arg.AppUserAttributesMode,
		arg.ID,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.EmailFooter,
		&i.EmailFont,
		&i.AppUserAuthority,
		&i.AppUserIngestUpsertKey,
		&i.AppUserAttributesMode,
	)
	return i, err
}
