// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation_inbound_hooks.sql

package sqlc

import (
	"context"
)

const getOrganisationInboundHook = `-- name: GetOrganisationInboundHook :one
SELECT organisation_id, secret, status, updated_at
FROM organisation_inbound_hooks
WHERE organisation_id = $1
`

func (q *Queries) GetOrganisationInboundHook(ctx context.Context, organisationID string) (OrganisationInboundHook, error) {
	row := q.db.QueryRow(ctx, getOrganisationInboundHook, organisationID)
	var i OrganisationInboundHook
	err := row.Scan(
		&i.OrganisationID,
		&i.Secret,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganisationInboundHook = `-- name: UpsertOrganisationInboundHook :one
INSERT INTO organisation_inbound_hooks (organisation_id, secret, status, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (organisation_id) DO UPDATE SET
    secret = EXCLUDED.secret,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING organisation_id, secret, status, updated_at
`

type UpsertOrganisationInboundHookParams struct {
	OrganisationID string `json:"organisation_id"`
	Secret         string `json:"secret"`
	Status         string `json:"status"`
}

func (q *Queries) UpsertOrganisationInboundHook(ctx context.Context, arg UpsertOrganisationInboundHookParams) (OrganisationInboundHook, error) {
	row := q.db.QueryRow(ctx, upsertOrganisationInboundHook, arg.OrganisationID, arg.Secret, arg.Status)
	var i OrganisationInboundHook
	err := row.Scan(
		&i.OrganisationID,
		&i.Secret,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
