// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation_inbound_webhooks.sql

package sqlc

import (
	"context"
)

const createOrganisationInboundWebhook = `-- name: CreateOrganisationInboundWebhook :one
INSERT INTO organisation_inbound_webhooks (
    id, organisation_id, name, secret, status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, organisation_id, name, secret, status, created_at, updated_at
`

type CreateOrganisationInboundWebhookParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Name           string `json:"name"`
	Secret         string `json:"secret"`
	Status         string `json:"status"`
}

func (q *Queries) CreateOrganisationInboundWebhook(ctx context.Context, arg CreateOrganisationInboundWebhookParams) (OrganisationInboundWebhook, error) {
	row := q.db.QueryRow(ctx, createOrganisationInboundWebhook,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Secret,
		arg.Status,
	)
	var i OrganisationInboundWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganisationInboundWebhook = `-- name: DeleteOrganisationInboundWebhook :exec
DELETE FROM organisation_inbound_webhooks
WHERE id = $1 AND organisation_id = $2
`

type DeleteOrganisationInboundWebhookParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteOrganisationInboundWebhook(ctx context.Context, arg DeleteOrganisationInboundWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteOrganisationInboundWebhook, arg.ID, arg.OrganisationID)
	return err
}

const getOrganisationInboundWebhook = `-- name: GetOrganisationInboundWebhook :one
SELECT id, organisation_id, name, secret, status, created_at, updated_at FROM organisation_inbound_webhooks
WHERE id = $1
`

func (q *Queries) GetOrganisationInboundWebhook(ctx context.Context, id string) (OrganisationInboundWebhook, error) {
	row := q.db.QueryRow(ctx, getOrganisationInboundWebhook, id)
	var i OrganisationInboundWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganisationInboundWebhookForOrg = `-- name: GetOrganisationInboundWebhookForOrg :one
SELECT id, organisation_id, name, secret, status, created_at, updated_at FROM organisation_inbound_webhooks
WHERE id = $1 AND organisation_id = $2
`

type GetOrganisationInboundWebhookForOrgParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) GetOrganisationInboundWebhookForOrg(ctx context.Context, arg GetOrganisationInboundWebhookForOrgParams) (OrganisationInboundWebhook, error) {
	row := q.db.QueryRow(ctx, getOrganisationInboundWebhookForOrg, arg.ID, arg.OrganisationID)
	var i OrganisationInboundWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisationInboundWebhooks = `-- name: ListOrganisationInboundWebhooks :many
SELECT id, organisation_id, name, secret, status, created_at, updated_at FROM organisation_inbound_webhooks
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrganisationInboundWebhooks(ctx context.Context, organisationID string) ([]OrganisationInboundWebhook, error) {
	rows, err := q.db.Query(ctx, listOrganisationInboundWebhooks, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationInboundWebhook{}
	for rows.Next() {
		var i OrganisationInboundWebhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Secret,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisationInboundWebhook = `-- name: UpdateOrganisationInboundWebhook :one
UPDATE organisation_inbound_webhooks SET
    name = $3,
    secret = $4,
    status = $5,
    updated_at = now()
WHERE id = $1 AND organisation_id = $2
RETURNING id, organisation_id, name, secret, status, created_at, updated_at
`

type UpdateOrganisationInboundWebhookParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Name           string `json:"name"`
	Secret         string `json:"secret"`
	Status         string `json:"status"`
}

func (q *Queries) UpdateOrganisationInboundWebhook(ctx context.Context, arg UpdateOrganisationInboundWebhookParams) (OrganisationInboundWebhook, error) {
	row := q.db.QueryRow(ctx, updateOrganisationInboundWebhook,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Secret,
		arg.Status,
	)
	var i OrganisationInboundWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
