// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation_webhooks.sql

package sqlc

import (
	"context"
)

const createOrganisationWebhook = `-- name: CreateOrganisationWebhook :one
INSERT INTO organisation_webhooks (
    id, organisation_id, name, url, secret, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, organisation_id, name, url, secret, status, created_at, updated_at
`

type CreateOrganisationWebhookParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Name           string `json:"name"`
	Url            string `json:"url"`
	Secret         string `json:"secret"`
	Status         string `json:"status"`
}

func (q *Queries) CreateOrganisationWebhook(ctx context.Context, arg CreateOrganisationWebhookParams) (OrganisationWebhook, error) {
	row := q.db.QueryRow(ctx, createOrganisationWebhook,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Status,
	)
	var i OrganisationWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganisationWebhook = `-- name: DeleteOrganisationWebhook :exec
DELETE FROM organisation_webhooks
WHERE id = $1 AND organisation_id = $2
`

type DeleteOrganisationWebhookParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteOrganisationWebhook(ctx context.Context, arg DeleteOrganisationWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteOrganisationWebhook, arg.ID, arg.OrganisationID)
	return err
}

const getOrganisationWebhook = `-- name: GetOrganisationWebhook :one
SELECT id, organisation_id, name, url, secret, status, created_at, updated_at FROM organisation_webhooks
WHERE id = $1
`

func (q *Queries) GetOrganisationWebhook(ctx context.Context, id string) (OrganisationWebhook, error) {
	row := q.db.QueryRow(ctx, getOrganisationWebhook, id)
	var i OrganisationWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganisationWebhookForOrg = `-- name: GetOrganisationWebhookForOrg :one
SELECT id, organisation_id, name, url, secret, status, created_at, updated_at FROM organisation_webhooks
WHERE id = $1 AND organisation_id = $2
`

type GetOrganisationWebhookForOrgParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) GetOrganisationWebhookForOrg(ctx context.Context, arg GetOrganisationWebhookForOrgParams) (OrganisationWebhook, error) {
	row := q.db.QueryRow(ctx, getOrganisationWebhookForOrg, arg.ID, arg.OrganisationID)
	var i OrganisationWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisationWebhooks = `-- name: ListOrganisationWebhooks :many
SELECT id, organisation_id, name, url, secret, status, created_at, updated_at FROM organisation_webhooks
WHERE organisation_id = $1
ORDER BY name, created_at
`

func (q *Queries) ListOrganisationWebhooks(ctx context.Context, organisationID string) ([]OrganisationWebhook, error) {
	rows, err := q.db.Query(ctx, listOrganisationWebhooks, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationWebhook{}
	for rows.Next() {
		var i OrganisationWebhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisationWebhook = `-- name: UpdateOrganisationWebhook :one
UPDATE organisation_webhooks
SET name = $1,
    url = $2,
    secret = CASE
        WHEN $3::text = '' THEN secret
        ELSE $3::text
    END,
    status = $4,
    updated_at = now()
WHERE id = $5 AND organisation_id = $6
RETURNING id, organisation_id, name, url, secret, status, created_at, updated_at
`

type UpdateOrganisationWebhookParams struct {
	Name           string `json:"name"`
	Url            string `json:"url"`
	Secret         string `json:"secret"`
	Status         string `json:"status"`
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) UpdateOrganisationWebhook(ctx context.Context, arg UpdateOrganisationWebhookParams) (OrganisationWebhook, error) {
	row := q.db.QueryRow(ctx, updateOrganisationWebhook,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Status,
		arg.ID,
		arg.OrganisationID,
	)
	var i OrganisationWebhook
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
