// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_features.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductPlanFeature = `-- name: AddProductPlanFeature :exec
INSERT INTO product_plan_features (product_plan_id, entitlement_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductPlanFeatureParams struct {
	ProductPlanID string `json:"product_plan_id"`
	EntitlementID string `json:"entitlement_id"`
}

func (q *Queries) AddProductPlanFeature(ctx context.Context, arg AddProductPlanFeatureParams) error {
	_, err := q.db.Exec(ctx, addProductPlanFeature, arg.ProductPlanID, arg.EntitlementID)
	return err
}

const clearOrganisationProductPlan = `-- name: ClearOrganisationProductPlan :exec
DELETE FROM organisation_product_plans
WHERE organisation_id = $1
`

func (q *Queries) ClearOrganisationProductPlan(ctx context.Context, organisationID string) error {
	_, err := q.db.Exec(ctx, clearOrganisationProductPlan, organisationID)
	return err
}

const createProductFeature = `-- name: CreateProductFeature :one
INSERT INTO entitlements (id, key, description, scope, organisation_id)
VALUES ($1, $2, $3, 'product', $4)
RETURNING id, key, description, scope, organisation_id
`

type CreateProductFeatureParams struct {
	ID             string      `json:"id"`
	Key            string      `json:"key"`
	Description    string      `json:"description"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

func (q *Queries) CreateProductFeature(ctx context.Context, arg CreateProductFeatureParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, createProductFeature,
		arg.ID,
		arg.Key,
		arg.Description,
		arg.OrganisationID,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Scope,
		&i.OrganisationID,
	)
	return i, err
}

const createProductPlan = `-- name: CreateProductPlan :one
INSERT INTO product_plans (id, organisation_id, key, name, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, key, name, status, created_at, updated_at
`

type CreateProductPlanParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Status         string `json:"status"`
}

func (q *Queries) CreateProductPlan(ctx context.Context, arg CreateProductPlanParams) (ProductPlan, error) {
	row := q.db.QueryRow(ctx, createProductPlan,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Status,
	)
	var i ProductPlan
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductFeature = `-- name: DeleteProductFeature :exec
DELETE FROM entitlements
WHERE id = $1
  AND organisation_id = $2
  AND scope = 'product'
`

type DeleteProductFeatureParams struct {
	ID             string      `json:"id"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

func (q *Queries) DeleteProductFeature(ctx context.Context, arg DeleteProductFeatureParams) error {
	_, err := q.db.Exec(ctx, deleteProductFeature, arg.ID, arg.OrganisationID)
	return err
}

const deleteProductPlan = `-- name: DeleteProductPlan :exec
DELETE FROM product_plans
WHERE id = $1
  AND organisation_id = $2
`

type DeleteProductPlanParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) DeleteProductPlan(ctx context.Context, arg DeleteProductPlanParams) error {
	_, err := q.db.Exec(ctx, deleteProductPlan, arg.ID, arg.OrganisationID)
	return err
}

const deleteProductPlanFeatures = `-- name: DeleteProductPlanFeatures :exec
DELETE FROM product_plan_features
WHERE product_plan_id = $1
`

func (q *Queries) DeleteProductPlanFeatures(ctx context.Context, productPlanID string) error {
	_, err := q.db.Exec(ctx, deleteProductPlanFeatures, productPlanID)
	return err
}

const getEntitlement = `-- name: GetEntitlement :one
SELECT id, key, description, scope, organisation_id FROM entitlements
WHERE id = $1
`

func (q *Queries) GetEntitlement(ctx context.Context, id string) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlement, id)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Scope,
		&i.OrganisationID,
	)
	return i, err
}

const getEntitlementForOrgCheck = `-- name: GetEntitlementForOrgCheck :one
SELECT id, key, description, scope, organisation_id
FROM entitlements
WHERE key = $1
  AND (organisation_id IS NULL OR organisation_id = $2)
ORDER BY (organisation_id IS NOT NULL) DESC
LIMIT 1
`

type GetEntitlementForOrgCheckParams struct {
	Key            string      `json:"key"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

func (q *Queries) GetEntitlementForOrgCheck(ctx context.Context, arg GetEntitlementForOrgCheckParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlementForOrgCheck, arg.Key, arg.OrganisationID)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Scope,
		&i.OrganisationID,
	)
	return i, err
}

const getOrganisationProductPlan = `-- name: GetOrganisationProductPlan :one
SELECT organisation_id, product_plan_id, updated_at FROM organisation_product_plans
WHERE organisation_id = $1
`

func (q *Queries) GetOrganisationProductPlan(ctx context.Context, organisationID string) (OrganisationProductPlan, error) {
	row := q.db.QueryRow(ctx, getOrganisationProductPlan, organisationID)
	var i OrganisationProductPlan
	err := row.Scan(&i.OrganisationID, &i.ProductPlanID, &i.UpdatedAt)
	return i, err
}

const getProductPlan = `-- name: GetProductPlan :one
SELECT id, organisation_id, key, name, status, created_at, updated_at FROM product_plans
WHERE id = $1
`

func (q *Queries) GetProductPlan(ctx context.Context, id string) (ProductPlan, error) {
	row := q.db.QueryRow(ctx, getProductPlan, id)
	var i ProductPlan
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitlementIDsByKeysForOrg = `-- name: ListEntitlementIDsByKeysForOrg :many
SELECT DISTINCT ON (key) id, key
FROM entitlements
WHERE key = ANY($1::text[])
  AND (organisation_id IS NULL OR organisation_id = $2)
ORDER BY key, (organisation_id IS NOT NULL) DESC
`

type ListEntitlementIDsByKeysForOrgParams struct {
	Keys           []string    `json:"keys"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

type ListEntitlementIDsByKeysForOrgRow struct {
	ID  string `json:"id"`
	Key string `json:"key"`
}

func (q *Queries) ListEntitlementIDsByKeysForOrg(ctx context.Context, arg ListEntitlementIDsByKeysForOrgParams) ([]ListEntitlementIDsByKeysForOrgRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementIDsByKeysForOrg, arg.Keys, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementIDsByKeysForOrgRow{}
	for rows.Next() {
		var i ListEntitlementIDsByKeysForOrgRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitlementScopesByKeysForOrg = `-- name: ListEntitlementScopesByKeysForOrg :many
SELECT DISTINCT ON (key) key, scope
FROM entitlements
WHERE key = ANY($1::text[])
  AND (organisation_id IS NULL OR organisation_id = $2)
ORDER BY key, (organisation_id IS NOT NULL) DESC
`

type ListEntitlementScopesByKeysForOrgParams struct {
	Keys           []string    `json:"keys"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

type ListEntitlementScopesByKeysForOrgRow struct {
	Key   string `json:"key"`
	Scope string `json:"scope"`
}

func (q *Queries) ListEntitlementScopesByKeysForOrg(ctx context.Context, arg ListEntitlementScopesByKeysForOrgParams) ([]ListEntitlementScopesByKeysForOrgRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementScopesByKeysForOrg, arg.Keys, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementScopesByKeysForOrgRow{}
	for rows.Next() {
		var i ListEntitlementScopesByKeysForOrgRow
		if err := rows.Scan(&i.Key, &i.Scope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductFeaturesByOrg = `-- name: ListProductFeaturesByOrg :many
SELECT id, key, description, scope, organisation_id FROM entitlements
WHERE organisation_id = $1
  AND scope = 'product'
ORDER BY key
`

func (q *Queries) ListProductFeaturesByOrg(ctx context.Context, organisationID pgtype.Text) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listProductFeaturesByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.Scope,
			&i.OrganisationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPlanFeatureKeys = `-- name: ListProductPlanFeatureKeys :many
SELECT e.key
FROM product_plan_features ppf
JOIN entitlements e ON e.id = ppf.entitlement_id
WHERE ppf.product_plan_id = $1
ORDER BY e.key
`

func (q *Queries) ListProductPlanFeatureKeys(ctx context.Context, productPlanID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listProductPlanFeatureKeys, productPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPlansByOrg = `-- name: ListProductPlansByOrg :many
SELECT id, organisation_id, key, name, status, created_at, updated_at FROM product_plans
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListProductPlansByOrg(ctx context.Context, organisationID string) ([]ProductPlan, error) {
	rows, err := q.db.Query(ctx, listProductPlansByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPlan{}
	for rows.Next() {
		var i ProductPlan
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductFeature = `-- name: UpdateProductFeature :one
UPDATE entitlements
SET description = $2
WHERE id = $1
  AND organisation_id = $3
  AND scope = 'product'
RETURNING id, key, description, scope, organisation_id
`

type UpdateProductFeatureParams struct {
	ID             string      `json:"id"`
	Description    string      `json:"description"`
	OrganisationID pgtype.Text `json:"organisation_id"`
}

func (q *Queries) UpdateProductFeature(ctx context.Context, arg UpdateProductFeatureParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, updateProductFeature, arg.ID, arg.Description, arg.OrganisationID)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Scope,
		&i.OrganisationID,
	)
	return i, err
}

const updateProductPlan = `-- name: UpdateProductPlan :one
UPDATE product_plans
SET name = COALESCE($2, name),
    status = COALESCE($3, status),
    updated_at = now()
WHERE id = $1
RETURNING id, organisation_id, key, name, status, created_at, updated_at
`

type UpdateProductPlanParams struct {
	ID     string      `json:"id"`
	Name   pgtype.Text `json:"name"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateProductPlan(ctx context.Context, arg UpdateProductPlanParams) (ProductPlan, error) {
	row := q.db.QueryRow(ctx, updateProductPlan, arg.ID, arg.Name, arg.Status)
	var i ProductPlan
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganisationProductPlan = `-- name: UpsertOrganisationProductPlan :one
INSERT INTO organisation_product_plans (organisation_id, product_plan_id, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (organisation_id) DO UPDATE
SET product_plan_id = EXCLUDED.product_plan_id,
    updated_at = now()
RETURNING organisation_id, product_plan_id, updated_at
`

type UpsertOrganisationProductPlanParams struct {
	OrganisationID string `json:"organisation_id"`
	ProductPlanID  string `json:"product_plan_id"`
}

func (q *Queries) UpsertOrganisationProductPlan(ctx context.Context, arg UpsertOrganisationProductPlanParams) (OrganisationProductPlan, error) {
	row := q.db.QueryRow(ctx, upsertOrganisationProductPlan, arg.OrganisationID, arg.ProductPlanID)
	var i OrganisationProductPlan
	err := row.Scan(&i.OrganisationID, &i.ProductPlanID, &i.UpdatedAt)
	return i, err
}
