// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_plan_prices.sql

package sqlc

import (
	"context"
)

const getProductPlanPrice = `-- name: GetProductPlanPrice :one
SELECT id, product_plan_id, interval, currency, unit_amount, processor, processor_product_ref, processor_price_ref, status FROM product_plan_prices
WHERE id = $1
`

func (q *Queries) GetProductPlanPrice(ctx context.Context, id string) (ProductPlanPrice, error) {
	row := q.db.QueryRow(ctx, getProductPlanPrice, id)
	var i ProductPlanPrice
	err := row.Scan(
		&i.ID,
		&i.ProductPlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorProductRef,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const getProductPlanPriceByPlanInterval = `-- name: GetProductPlanPriceByPlanInterval :one
SELECT id, product_plan_id, interval, currency, unit_amount, processor, processor_product_ref, processor_price_ref, status FROM product_plan_prices
WHERE product_plan_id = $1
  AND interval = $2
  AND processor = $3
`

type GetProductPlanPriceByPlanIntervalParams struct {
	ProductPlanID string `json:"product_plan_id"`
	Interval      string `json:"interval"`
	Processor     string `json:"processor"`
}

func (q *Queries) GetProductPlanPriceByPlanInterval(ctx context.Context, arg GetProductPlanPriceByPlanIntervalParams) (ProductPlanPrice, error) {
	row := q.db.QueryRow(ctx, getProductPlanPriceByPlanInterval, arg.ProductPlanID, arg.Interval, arg.Processor)
	var i ProductPlanPrice
	err := row.Scan(
		&i.ID,
		&i.ProductPlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorProductRef,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const getProductPlanPriceByProcessorRef = `-- name: GetProductPlanPriceByProcessorRef :one
SELECT id, product_plan_id, interval, currency, unit_amount, processor, processor_product_ref, processor_price_ref, status FROM product_plan_prices
WHERE processor = $1
  AND processor_price_ref = $2
`

type GetProductPlanPriceByProcessorRefParams struct {
	Processor         string `json:"processor"`
	ProcessorPriceRef string `json:"processor_price_ref"`
}

func (q *Queries) GetProductPlanPriceByProcessorRef(ctx context.Context, arg GetProductPlanPriceByProcessorRefParams) (ProductPlanPrice, error) {
	row := q.db.QueryRow(ctx, getProductPlanPriceByProcessorRef, arg.Processor, arg.ProcessorPriceRef)
	var i ProductPlanPrice
	err := row.Scan(
		&i.ID,
		&i.ProductPlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorProductRef,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}

const listProductPlanPricesByOrg = `-- name: ListProductPlanPricesByOrg :many
SELECT ppp.id, ppp.product_plan_id, ppp.interval, ppp.currency, ppp.unit_amount, ppp.processor, ppp.processor_product_ref, ppp.processor_price_ref, ppp.status
FROM product_plan_prices ppp
JOIN product_plans pp ON pp.id = ppp.product_plan_id
WHERE pp.organisation_id = $1
ORDER BY pp.key, ppp.interval
`

func (q *Queries) ListProductPlanPricesByOrg(ctx context.Context, organisationID string) ([]ProductPlanPrice, error) {
	rows, err := q.db.Query(ctx, listProductPlanPricesByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPlanPrice{}
	for rows.Next() {
		var i ProductPlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.ProductPlanID,
			&i.Interval,
			&i.Currency,
			&i.UnitAmount,
			&i.Processor,
			&i.ProcessorProductRef,
			&i.ProcessorPriceRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPlanPricesByPlan = `-- name: ListProductPlanPricesByPlan :many
SELECT id, product_plan_id, interval, currency, unit_amount, processor, processor_product_ref, processor_price_ref, status FROM product_plan_prices
WHERE product_plan_id = $1
ORDER BY interval
`

func (q *Queries) ListProductPlanPricesByPlan(ctx context.Context, productPlanID string) ([]ProductPlanPrice, error) {
	rows, err := q.db.Query(ctx, listProductPlanPricesByPlan, productPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPlanPrice{}
	for rows.Next() {
		var i ProductPlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.ProductPlanID,
			&i.Interval,
			&i.Currency,
			&i.UnitAmount,
			&i.Processor,
			&i.ProcessorProductRef,
			&i.ProcessorPriceRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsyncedProductPlanPricesByOrg = `-- name: ListUnsyncedProductPlanPricesByOrg :many
SELECT ppp.id, ppp.product_plan_id, ppp.interval, ppp.currency, ppp.unit_amount, ppp.processor, ppp.processor_product_ref, ppp.processor_price_ref, ppp.status
FROM product_plan_prices ppp
JOIN product_plans pp ON pp.id = ppp.product_plan_id
WHERE pp.organisation_id = $1
  AND ppp.processor = $2
  AND ppp.status = 'active'
  AND (ppp.processor_price_ref = '' OR ppp.processor_product_ref = '')
ORDER BY pp.key, ppp.interval
`

type ListUnsyncedProductPlanPricesByOrgParams struct {
	OrganisationID string `json:"organisation_id"`
	Processor      string `json:"processor"`
}

func (q *Queries) ListUnsyncedProductPlanPricesByOrg(ctx context.Context, arg ListUnsyncedProductPlanPricesByOrgParams) ([]ProductPlanPrice, error) {
	rows, err := q.db.Query(ctx, listUnsyncedProductPlanPricesByOrg, arg.OrganisationID, arg.Processor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPlanPrice{}
	for rows.Next() {
		var i ProductPlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.ProductPlanID,
			&i.Interval,
			&i.Currency,
			&i.UnitAmount,
			&i.Processor,
			&i.ProcessorProductRef,
			&i.ProcessorPriceRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductPlanPrice = `-- name: UpsertProductPlanPrice :one
INSERT INTO product_plan_prices (
    id, product_plan_id, interval, currency, unit_amount, processor,
    processor_product_ref, processor_price_ref, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (product_plan_id, interval, processor) DO UPDATE
SET currency = EXCLUDED.currency,
    unit_amount = EXCLUDED.unit_amount,
    processor_product_ref = EXCLUDED.processor_product_ref,
    processor_price_ref = EXCLUDED.processor_price_ref,
    status = EXCLUDED.status
RETURNING id, product_plan_id, interval, currency, unit_amount, processor, processor_product_ref, processor_price_ref, status
`

type UpsertProductPlanPriceParams struct {
	ID                  string `json:"id"`
	ProductPlanID       string `json:"product_plan_id"`
	Interval            string `json:"interval"`
	Currency            string `json:"currency"`
	UnitAmount          int64  `json:"unit_amount"`
	Processor           string `json:"processor"`
	ProcessorProductRef string `json:"processor_product_ref"`
	ProcessorPriceRef   string `json:"processor_price_ref"`
	Status              string `json:"status"`
}

func (q *Queries) UpsertProductPlanPrice(ctx context.Context, arg UpsertProductPlanPriceParams) (ProductPlanPrice, error) {
	row := q.db.QueryRow(ctx, upsertProductPlanPrice,
		arg.ID,
		arg.ProductPlanID,
		arg.Interval,
		arg.Currency,
		arg.UnitAmount,
		arg.Processor,
		arg.ProcessorProductRef,
		arg.ProcessorPriceRef,
		arg.Status,
	)
	var i ProductPlanPrice
	err := row.Scan(
		&i.ID,
		&i.ProductPlanID,
		&i.Interval,
		&i.Currency,
		&i.UnitAmount,
		&i.Processor,
		&i.ProcessorProductRef,
		&i.ProcessorPriceRef,
		&i.Status,
	)
	return i, err
}
