// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reach.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReachEdgesBySource = `-- name: CountReachEdgesBySource :many
SELECT source, count(*)::bigint AS total
FROM reach_edges
WHERE namespace = $1
GROUP BY source
ORDER BY source
`

type CountReachEdgesBySourceRow struct {
	Source string `json:"source"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountReachEdgesBySource(ctx context.Context, namespace string) ([]CountReachEdgesBySourceRow, error) {
	rows, err := q.db.Query(ctx, countReachEdgesBySource, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountReachEdgesBySourceRow{}
	for rows.Next() {
		var i CountReachEdgesBySourceRow
		if err := rows.Scan(&i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReachEdge = `-- name: DeleteReachEdge :exec
DELETE FROM reach_edges
WHERE namespace = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
  AND subject_type = $5
  AND subject_id = $6
  AND subject_relation = $7
`

type DeleteReachEdgeParams struct {
	Namespace       string `json:"namespace"`
	ObjectType      string `json:"object_type"`
	ObjectID        string `json:"object_id"`
	Relation        string `json:"relation"`
	SubjectType     string `json:"subject_type"`
	SubjectID       string `json:"subject_id"`
	SubjectRelation string `json:"subject_relation"`
}

func (q *Queries) DeleteReachEdge(ctx context.Context, arg DeleteReachEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteReachEdge,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
	)
	return err
}

const listReachEdges = `-- name: ListReachEdges :many

SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source, created_at FROM reach_edges
WHERE namespace = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
`

type ListReachEdgesParams struct {
	Namespace  string `json:"namespace"`
	ObjectType string `json:"object_type"`
	ObjectID   string `json:"object_id"`
	Relation   string `json:"relation"`
}

// Queries for the relation-graph edge table.
//
// ListReachEdges is the whole read path of the evaluator, and it is an exact
// prefix of the primary key, so it is an index lookup however large the table
// grows. Expiry is deliberately not filtered here: the evaluator is handed the
// time to decide against, so a test can pin it and production cannot disagree
// with itself between the query and the walk.
func (q *Queries) ListReachEdges(ctx context.Context, arg ListReachEdgesParams) ([]ReachEdge, error) {
	rows, err := q.db.Query(ctx, listReachEdges,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdge{}
	for rows.Next() {
		var i ReachEdge
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReachEdgesForSubject = `-- name: ListReachEdgesForSubject :many

SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source, created_at FROM reach_edges
WHERE namespace = $1 AND subject_type = $2 AND subject_id = $3
ORDER BY object_type, object_id, relation
`

type ListReachEdgesForSubjectParams struct {
	Namespace   string `json:"namespace"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

// ListReachEdgesForSubject is the sweep: every edge naming one principal. It is
// what offboarding uses, and it is the reason ownership can be lifecycle only.
func (q *Queries) ListReachEdgesForSubject(ctx context.Context, arg ListReachEdgesForSubjectParams) ([]ReachEdge, error) {
	rows, err := q.db.Query(ctx, listReachEdgesForSubject, arg.Namespace, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdge{}
	for rows.Next() {
		var i ReachEdge
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeReachEdge = `-- name: WriteReachEdge :exec
INSERT INTO reach_edges (
    namespace, object_type, object_id, relation,
    subject_type, subject_id, subject_relation, expires_at, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation)
DO UPDATE SET expires_at = EXCLUDED.expires_at, source = EXCLUDED.source
`

type WriteReachEdgeParams struct {
	Namespace       string             `json:"namespace"`
	ObjectType      string             `json:"object_type"`
	ObjectID        string             `json:"object_id"`
	Relation        string             `json:"relation"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	SubjectRelation string             `json:"subject_relation"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Source          string             `json:"source"`
}

func (q *Queries) WriteReachEdge(ctx context.Context, arg WriteReachEdgeParams) error {
	_, err := q.db.Exec(ctx, writeReachEdge,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
		arg.ExpiresAt,
		arg.Source,
	)
	return err
}
