// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reach.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReachEdgesBySource = `-- name: CountReachEdgesBySource :many
SELECT source, count(*)::bigint AS total
FROM reach_edges
WHERE namespace = $1
GROUP BY source
ORDER BY source
`

type CountReachEdgesBySourceRow struct {
	Source string `json:"source"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountReachEdgesBySource(ctx context.Context, namespace string) ([]CountReachEdgesBySourceRow, error) {
	rows, err := q.db.Query(ctx, countReachEdgesBySource, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountReachEdgesBySourceRow{}
	for rows.Next() {
		var i CountReachEdgesBySourceRow
		if err := rows.Scan(&i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReachEdge = `-- name: DeleteReachEdge :exec
DELETE FROM reach_edges
WHERE namespace = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
  AND subject_type = $5
  AND subject_id = $6
  AND subject_relation = $7
`

type DeleteReachEdgeParams struct {
	Namespace       string `json:"namespace"`
	ObjectType      string `json:"object_type"`
	ObjectID        string `json:"object_id"`
	Relation        string `json:"relation"`
	SubjectType     string `json:"subject_type"`
	SubjectID       string `json:"subject_id"`
	SubjectRelation string `json:"subject_relation"`
}

func (q *Queries) DeleteReachEdge(ctx context.Context, arg DeleteReachEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteReachEdge,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
	)
	return err
}

const listLiveEdges = `-- name: ListLiveEdges :many

SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source FROM reach_edges_live
WHERE namespace = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
`

type ListLiveEdgesParams struct {
	Namespace  string `json:"namespace"`
	ObjectType string `json:"object_type"`
	ObjectID   string `json:"object_id"`
	Relation   string `json:"relation"`
}

// ListLiveEdges reads the view that presents the current authorisation tables
// as edges, unioned with any edge written directly. This is the evaluator's
// source during the cutover: it reads the same rows the previous engine read,
// so the two cannot disagree about state, only about how state is interpreted.
func (q *Queries) ListLiveEdges(ctx context.Context, arg ListLiveEdgesParams) ([]ReachEdgesLive, error) {
	rows, err := q.db.Query(ctx, listLiveEdges,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdgesLive{}
	for rows.Next() {
		var i ReachEdgesLive
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveEdgesForSubject = `-- name: ListLiveEdgesForSubject :many
SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source FROM reach_edges_live
WHERE namespace = $1 AND subject_type = $2 AND subject_id = $3
ORDER BY object_type, object_id, relation
`

type ListLiveEdgesForSubjectParams struct {
	Namespace   string `json:"namespace"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

func (q *Queries) ListLiveEdgesForSubject(ctx context.Context, arg ListLiveEdgesForSubjectParams) ([]ReachEdgesLive, error) {
	rows, err := q.db.Query(ctx, listLiveEdgesForSubject, arg.Namespace, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdgesLive{}
	for rows.Next() {
		var i ReachEdgesLive
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorRoleHierarchy = `-- name: ListOperatorRoleHierarchy :many
SELECT r.id, r.key, r.name,
       COALESCE(ARRAY(
         SELECT p.key FROM role_extends e
         JOIN roles p ON p.id = e.parent_id
         WHERE e.role_id = r.id
         ORDER BY p.key
       ), '{}')::text[] AS parent_keys,
       COALESCE(ARRAY(
         SELECT pm.key FROM role_permissions rp
         JOIN permissions pm ON pm.id = rp.permission_id
         WHERE rp.role_id = r.id
         ORDER BY pm.key
       ), '{}')::text[] AS permission_keys
FROM roles r
WHERE r.organisation_id = $1
ORDER BY r.key
`

type ListOperatorRoleHierarchyRow struct {
	ID             string   `json:"id"`
	Key            string   `json:"key"`
	Name           string   `json:"name"`
	ParentKeys     []string `json:"parent_keys"`
	PermissionKeys []string `json:"permission_keys"`
}

// ListOperatorRoleHierarchy answers "what do owner, admin and member actually
// mean here?", which the schema map cannot: those three are rows, not types.
//
// The chain was real in the database from the moment role_extends landed and
// visible nowhere, because the operator roles UI is hidden and a membership
// shows only its own role key.
func (q *Queries) ListOperatorRoleHierarchy(ctx context.Context, organisationID string) ([]ListOperatorRoleHierarchyRow, error) {
	rows, err := q.db.Query(ctx, listOperatorRoleHierarchy, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorRoleHierarchyRow{}
	for rows.Next() {
		var i ListOperatorRoleHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.ParentKeys,
			&i.PermissionKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReachEdges = `-- name: ListReachEdges :many

SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source, created_at FROM reach_edges
WHERE namespace = $1
  AND object_type = $2
  AND object_id = $3
  AND relation = $4
`

type ListReachEdgesParams struct {
	Namespace  string `json:"namespace"`
	ObjectType string `json:"object_type"`
	ObjectID   string `json:"object_id"`
	Relation   string `json:"relation"`
}

// Queries for the relation-graph edge table.
//
// ListReachEdges is the whole read path of the evaluator, and it is an exact
// prefix of the primary key, so it is an index lookup however large the table
// grows. Expiry is deliberately not filtered here: the evaluator is handed the
// time to decide against, so a test can pin it and production cannot disagree
// with itself between the query and the walk.
func (q *Queries) ListReachEdges(ctx context.Context, arg ListReachEdgesParams) ([]ReachEdge, error) {
	rows, err := q.db.Query(ctx, listReachEdges,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdge{}
	for rows.Next() {
		var i ReachEdge
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReachEdgesForSubject = `-- name: ListReachEdgesForSubject :many

SELECT namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation, expires_at, source, created_at FROM reach_edges
WHERE namespace = $1 AND subject_type = $2 AND subject_id = $3
ORDER BY object_type, object_id, relation
`

type ListReachEdgesForSubjectParams struct {
	Namespace   string `json:"namespace"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

// ListReachEdgesForSubject is the sweep: every edge naming one principal. It is
// what offboarding uses, and it is the reason ownership can be lifecycle only.
func (q *Queries) ListReachEdgesForSubject(ctx context.Context, arg ListReachEdgesForSubjectParams) ([]ReachEdge, error) {
	rows, err := q.db.Query(ctx, listReachEdgesForSubject, arg.Namespace, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReachEdge{}
	for rows.Next() {
		var i ReachEdge
		if err := rows.Scan(
			&i.Namespace,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeReachEdge = `-- name: WriteReachEdge :exec
INSERT INTO reach_edges (
    namespace, object_type, object_id, relation,
    subject_type, subject_id, subject_relation, expires_at, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (namespace, object_type, object_id, relation, subject_type, subject_id, subject_relation)
DO UPDATE SET expires_at = EXCLUDED.expires_at, source = EXCLUDED.source
`

type WriteReachEdgeParams struct {
	Namespace       string             `json:"namespace"`
	ObjectType      string             `json:"object_type"`
	ObjectID        string             `json:"object_id"`
	Relation        string             `json:"relation"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	SubjectRelation string             `json:"subject_relation"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Source          string             `json:"source"`
}

func (q *Queries) WriteReachEdge(ctx context.Context, arg WriteReachEdgeParams) error {
	_, err := q.db.Exec(ctx, writeReachEdge,
		arg.Namespace,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
		arg.ExpiresAt,
		arg.Source,
	)
	return err
}
