// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package sqlc

import (
	"context"
	"time"
)

const createRecoveryCredential = `-- name: CreateRecoveryCredential :one
INSERT INTO recovery_credentials (id, name, token_prefix, token_hash, granted_by, reason, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, token_prefix, token_hash, granted_by, reason, expires_at, revoked_at, last_used_at, created_at
`

type CreateRecoveryCredentialParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	TokenPrefix string    `json:"token_prefix"`
	TokenHash   string    `json:"token_hash"`
	GrantedBy   string    `json:"granted_by"`
	Reason      string    `json:"reason"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateRecoveryCredential(ctx context.Context, arg CreateRecoveryCredentialParams) (RecoveryCredential, error) {
	row := q.db.QueryRow(ctx, createRecoveryCredential,
		arg.ID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.GrantedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i RecoveryCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.GrantedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLiveRecoveryCredentialByHash = `-- name: GetLiveRecoveryCredentialByHash :one
SELECT id, name, token_prefix, token_hash, granted_by, reason, expires_at, revoked_at, last_used_at, created_at FROM recovery_credentials
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// GetLiveRecoveryCredentialByHash resolves a credential only while it is usable.
// Expiry and revocation are enforced in SQL so no caller can forget them.
func (q *Queries) GetLiveRecoveryCredentialByHash(ctx context.Context, tokenHash string) (RecoveryCredential, error) {
	row := q.db.QueryRow(ctx, getLiveRecoveryCredentialByHash, tokenHash)
	var i RecoveryCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.GrantedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryCredentials = `-- name: ListRecoveryCredentials :many
SELECT id, name, token_prefix, token_hash, granted_by, reason, expires_at, revoked_at, last_used_at, created_at FROM recovery_credentials
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecoveryCredentials(ctx context.Context, limit int32) ([]RecoveryCredential, error) {
	rows, err := q.db.Query(ctx, listRecoveryCredentials, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCredential{}
	for rows.Next() {
		var i RecoveryCredential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.GrantedBy,
			&i.Reason,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRecoveryCredential = `-- name: RevokeRecoveryCredential :one
UPDATE recovery_credentials
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, name, token_prefix, token_hash, granted_by, reason, expires_at, revoked_at, last_used_at, created_at
`

func (q *Queries) RevokeRecoveryCredential(ctx context.Context, id string) (RecoveryCredential, error) {
	row := q.db.QueryRow(ctx, revokeRecoveryCredential, id)
	var i RecoveryCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.GrantedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchRecoveryCredentialLastUsed = `-- name: TouchRecoveryCredentialLastUsed :exec
UPDATE recovery_credentials SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchRecoveryCredentialLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchRecoveryCredentialLastUsed, id)
	return err
}
