// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoleExtends = `-- name: AddRoleExtends :exec

INSERT INTO role_extends (role_id, parent_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoleExtendsParams struct {
	RoleID   string `json:"role_id"`
	ParentID string `json:"parent_id"`
}

// Role inheritance. The child gains what the parent holds, the same direction
// app_role_extends uses for the merchant tier.
func (q *Queries) AddRoleExtends(ctx context.Context, arg AddRoleExtendsParams) error {
	_, err := q.db.Exec(ctx, addRoleExtends, arg.RoleID, arg.ParentID)
	return err
}

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const checkUserPermission = `-- name: CheckUserPermission :one
SELECT EXISTS (
    SELECT 1
    FROM memberships m
    JOIN role_permissions rp ON rp.role_id = m.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE m.organisation_id = $1
      AND m.user_id = $2
      AND m.status = 'active'
      AND p.key = $3
) AS allowed
`

type CheckUserPermissionParams struct {
	OrganisationID string `json:"organisation_id"`
	UserID         string `json:"user_id"`
	PermissionKey  string `json:"permission_key"`
}

func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.OrganisationID, arg.UserID, arg.PermissionKey)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, organisation_id, key, name, description, is_system)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, key, name, description, is_system
`

type CreateRoleParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	IsSystem       bool   `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getPermissionByKey = `-- name: GetPermissionByKey :one
SELECT id, key, resource, action, category, description, is_system FROM permissions
WHERE key = $1
`

func (q *Queries) GetPermissionByKey(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByKey, key)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Resource,
		&i.Action,
		&i.Category,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getPermissionByResourceAction = `-- name: GetPermissionByResourceAction :one
SELECT id, key, resource, action, category, description, is_system FROM permissions
WHERE resource = $1 AND action = $2
`

type GetPermissionByResourceActionParams struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) GetPermissionByResourceAction(ctx context.Context, arg GetPermissionByResourceActionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByResourceAction, arg.Resource, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Resource,
		&i.Action,
		&i.Category,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getRoleByOrgAndKey = `-- name: GetRoleByOrgAndKey :one
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE organisation_id = $1 AND key = $2
`

type GetRoleByOrgAndKeyParams struct {
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
}

func (q *Queries) GetRoleByOrgAndKey(ctx context.Context, arg GetRoleByOrgAndKeyParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByOrgAndKey, arg.OrganisationID, arg.Key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const listPermissionIDs = `-- name: ListPermissionIDs :many
SELECT id FROM permissions
ORDER BY key
`

func (q *Queries) ListPermissionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionIDsByKeys = `-- name: ListPermissionIDsByKeys :many
SELECT id, key FROM permissions
WHERE key = ANY($1::text[])
ORDER BY key
`

type ListPermissionIDsByKeysRow struct {
	ID  string `json:"id"`
	Key string `json:"key"`
}

func (q *Queries) ListPermissionIDsByKeys(ctx context.Context, keys []string) ([]ListPermissionIDsByKeysRow, error) {
	rows, err := q.db.Query(ctx, listPermissionIDsByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionIDsByKeysRow{}
	for rows.Next() {
		var i ListPermissionIDsByKeysRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionKeysByRole = `-- name: ListPermissionKeysByRole :many
SELECT p.key
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.key
`

func (q *Queries) ListPermissionKeysByRole(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionKeysByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, resource, action, category, description, is_system FROM permissions
ORDER BY category, key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Resource,
			&i.Action,
			&i.Category,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsFiltered = `-- name: ListPermissionsFiltered :many
SELECT id, key, resource, action, category, description, is_system FROM permissions
WHERE ($1::text IS NULL OR category = $1)
  AND ($2::text IS NULL OR resource = $2)
ORDER BY category, key
`

type ListPermissionsFilteredParams struct {
	Category pgtype.Text `json:"category"`
	Resource pgtype.Text `json:"resource"`
}

func (q *Queries) ListPermissionsFiltered(ctx context.Context, arg ListPermissionsFilteredParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsFiltered, arg.Category, arg.Resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Resource,
			&i.Action,
			&i.Category,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleParents = `-- name: ListRoleParents :many
SELECT parent_id FROM role_extends WHERE role_id = $1 ORDER BY parent_id
`

func (q *Queries) ListRoleParents(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleParents, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_id string
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrganisation = `-- name: ListRolesByOrganisation :many
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListRolesByOrganisation(ctx context.Context, organisationID string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGlobalReach = `-- name: ListUserGlobalReach :many
SELECT m.id
FROM memberships m
WHERE m.user_id = $1
  AND m.status = 'active'
  AND (m.expires_at IS NULL OR m.expires_at > now())
  AND m.organisation_id = (SELECT platform_organisation_id FROM system_state WHERE id = 1)
`

// ListUserGlobalReach returns the user's live memberships of the platform
// organisation. Used to report staff status without naming any role.
func (q *Queries) ListUserGlobalReach(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserGlobalReach, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGrantSources = `-- name: ListUserGrantSources :many
SELECT
    m.organisation_id,
    COALESCE(m.organisation_id = (SELECT platform_organisation_id FROM system_state WHERE id = 1), false)::boolean AS global_reach,
    p.key AS permission_key
FROM memberships m
LEFT JOIN role_permissions rp ON rp.role_id = m.role_id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE m.user_id = $1
  AND m.status = 'active'
  AND (m.expires_at IS NULL OR m.expires_at > now())
  AND (
        m.organisation_id = $2
     OR m.organisation_id = (SELECT platform_organisation_id FROM system_state WHERE id = 1)
  )
ORDER BY m.organisation_id
`

type ListUserGrantSourcesParams struct {
	UserID         string `json:"user_id"`
	OrganisationID string `json:"organisation_id"`
}

type ListUserGrantSourcesRow struct {
	OrganisationID string      `json:"organisation_id"`
	GlobalReach    bool        `json:"global_reach"`
	PermissionKey  pgtype.Text `json:"permission_key"`
}

// ListUserGrantSources returns everything a user's memberships confer that is
// relevant to one organisation: that organisation's own membership, plus any
// membership of the platform organisation, which is what makes someone staff.
//
// Global reach is derived here, never stored. A role in a merchant organisation
// can therefore never produce one, whatever anybody sets on it.
//
// COALESCE keeps this failing closed: with no system_state row the comparison
// is NULL, and nobody gets reach.
//
// LEFT JOIN on purpose: a membership with a permissionless role still confers
// reach, and dropping it would make such a member invisible rather than
// powerless.
func (q *Queries) ListUserGrantSources(ctx context.Context, arg ListUserGrantSourcesParams) ([]ListUserGrantSourcesRow, error) {
	rows, err := q.db.Query(ctx, listUserGrantSources, arg.UserID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGrantSourcesRow{}
	for rows.Next() {
		var i ListUserGrantSourcesRow
		if err := rows.Scan(&i.OrganisationID, &i.GlobalReach, &i.PermissionKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleExtends = `-- name: RemoveRoleExtends :exec
DELETE FROM role_extends WHERE role_id = $1 AND parent_id = $2
`

type RemoveRoleExtendsParams struct {
	RoleID   string `json:"role_id"`
	ParentID string `json:"parent_id"`
}

func (q *Queries) RemoveRoleExtends(ctx context.Context, arg RemoveRoleExtendsParams) error {
	_, err := q.db.Exec(ctx, removeRoleExtends, arg.RoleID, arg.ParentID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET
  name = COALESCE($1, name),
  description = COALESCE($2, description)
WHERE id = $3
RETURNING id, organisation_id, key, name, description, is_system
`

type UpdateRoleParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          string      `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}
