// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, organisation_id, key, name, description, is_system)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, key, name, description, is_system
`

type CreateRoleParams struct {
	ID             string `json:"id"`
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	IsSystem       bool   `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.OrganisationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const getRoleByOrgAndKey = `-- name: GetRoleByOrgAndKey :one
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE organisation_id = $1 AND key = $2
`

type GetRoleByOrgAndKeyParams struct {
	OrganisationID string `json:"organisation_id"`
	Key            string `json:"key"`
}

func (q *Queries) GetRoleByOrgAndKey(ctx context.Context, arg GetRoleByOrgAndKeyParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByOrgAndKey, arg.OrganisationID, arg.Key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
	)
	return i, err
}

const listPermissionIDs = `-- name: ListPermissionIDs :many
SELECT id FROM permissions
ORDER BY key
`

func (q *Queries) ListPermissionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, resource, action, category, description, is_system FROM permissions
ORDER BY category, key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Resource,
			&i.Action,
			&i.Category,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrganisation = `-- name: ListRolesByOrganisation :many
SELECT id, organisation_id, key, name, description, is_system FROM roles
WHERE organisation_id = $1
ORDER BY key
`

func (q *Queries) ListRolesByOrganisation(ctx context.Context, organisationID string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
