// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, status, platform_admin, google_sub)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, status, created_at, updated_at, platform_admin, google_sub
`

type CreateUserParams struct {
	ID            string      `json:"id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	Status        string      `json:"status"`
	PlatformAdmin bool        `json:"platform_admin"`
	GoogleSub     pgtype.Text `json:"google_sub"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.PlatformAdmin,
		arg.GoogleSub,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformAdmin,
		&i.GoogleSub,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, status, created_at, updated_at, platform_admin, google_sub FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformAdmin,
		&i.GoogleSub,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, status, created_at, updated_at, platform_admin, google_sub FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformAdmin,
		&i.GoogleSub,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, name, status, created_at, updated_at, platform_admin, google_sub FROM users
WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformAdmin,
		&i.GoogleSub,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, status, created_at, updated_at, platform_admin, google_sub FROM users
WHERE (
    $1::text IS NULL
    OR name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
  )
  AND ($2::text IS NULL OR id > $2)
ORDER BY id
LIMIT $3
`

type ListUsersParams struct {
	Q      pgtype.Text `json:"q"`
	Cursor pgtype.Text `json:"cursor"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Q, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlatformAdmin,
			&i.GoogleSub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  name = COALESCE($1, name),
  status = COALESCE($2, status),
  platform_admin = COALESCE($3, platform_admin),
  google_sub = COALESCE($4, google_sub),
  updated_at = now()
WHERE id = $5
RETURNING id, email, name, status, created_at, updated_at, platform_admin, google_sub
`

type UpdateUserParams struct {
	Name          pgtype.Text `json:"name"`
	Status        pgtype.Text `json:"status"`
	PlatformAdmin pgtype.Bool `json:"platform_admin"`
	GoogleSub     pgtype.Text `json:"google_sub"`
	ID            string      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Status,
		arg.PlatformAdmin,
		arg.GoogleSub,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformAdmin,
		&i.GoogleSub,
	)
	return i, err
}
