// Package automations owns the merchant rule DSL (conditions, actions) and action/op
// catalogs. Trigger IDs are generated by core/resources (lifecycle + attribute
// expansion) and adapted via ExpandTriggers.
// Persistence and HTTP live in internal/store, internal/service, and internal/http.
package automations
